gulpfile.js
package.json

Added middleware to handle resolving /ipfs/ paths while running the gulp server.

Proxy /ipfs/ requests

---

js/views/object.jsx

Reference: https://github.com/jbenet/go-ipfs/pull/810

Fixed issue introduced in go-ipfs#810

---

js/views/object.jsx

This should fix https://github.com/jbenet/go-ipfs/issues/808.

Add proper UTF-8 support for file previews

---

package.json

Bump geoip version

---

js/views/page.jsx

Set gateway based on window hostname

---

less/bundle.less

Fix the position of the globe so it doesn't scroll, #57

Fixed Globe

---

js/views/page.jsx

change jbenet/ipfs to ipfs/webui

---

js/views/filelist.jsx
js/views/page.jsx

Hi, your DAG link was broken, it has to link to #/objects/object/{object.id}
BTW, your IPFS protocol is awesome =)

Fix DagPath on UI

---

js/pages/notfound.jsx

Updates the 'back to console home' link in the 404

---

app/scripts/pages/bitswap.js
app/scripts/pages/config.js
app/scripts/pages/connections.js
app/scripts/pages/files.js
app/scripts/pages/home.js
app/scripts/pages/logs.js
app/scripts/pages/notfound.js
app/scripts/pages/objects.js
app/scripts/pages/routing.js

Converted most of the BS elements to ReactBootstrap, as per #140. I did not do all of them - I am not sure how Button would react, for instance, and I want to make sure I do it right before I mess something up.

Converted majority of BS elements

---

README.md

Adds required configurations to run the WebUI on port 3000 so that it can properly make request to the running daemon.

Update README with Access-Control headers for development

---

webpack.config.js

fix: Ensure relative paths are working in resulting bundle

---

README.md

Filled out readme

---

README.md

https://github.com/ipfs/webui/issues/245#issuecomment-184569472
Specify which versions of node and npm to use for contributors.

specify node/npm versions

---

app/scripts/views/table.js
test/views/table.spec.js

https://github.com/ipfs/webui/issues/137
Adds a test for the table view.

add table spec

---

test/components/welcome.spec.js

https://github.com/ipfs/webui/issues/137

welcome component spec

---

app/scripts/components/world-map.js
app/scripts/components/world.js
test/components/world-map.spec.js
test/components/world.spec.js

rebases https://github.com/ipfs/webui/pull/253

world spec rebased

---

package.json
src/app/js/components/files/context-menu.js
src/app/js/components/files/tree.js

Adds copy hash to clipboard context menu item

---

dist/locale/webui-zh.json

There should not be an extra double quotation mark in line 3

fix: an error in webui-zh.json

---

package.json
src/app/js/components/files/tree.js
src/app/js/components/files/tree/row.js
src/app/js/containers/files-explorer.js
src/app/js/services/api.js

Closes #632 and closes #633.
Also: updates production dependencies.

fix: file explorer due to breaking change on ipfs-api

---

package.json
src/app/js/services/api.js

Fixes image previews.
Ref.: #642

fix: image previews

---

package.json
src/app/js/components/preview.js
src/app/js/containers/files-preview.js
src/app/js/sagas/pages/preview.js

feat: video, pdf and music previews

---

src/components/checkbox/Checkbox.js

You can use Checkbox in two ways:
```javascript
<Checkbox className='ma2' label='Click me!' onChange={fn} />
// This way, fn will receive as a parameter the new status of the button
```
```javascript
<Checkbox className='ma2' checked={checked} label='Click me!' onChange={fn} />
// This way, you tell if the checkbox is checked and fn is triggered to validate the change
// and you have to reactively update the checked info.
```

feat: checkbox controlled mode

---

src/App.js

feat: align margin

---

README.md

License: MIT
Signed-off-by: Adrian Lanzafame <adrianlanzafame92@gmail.com>

update repo url in install instructions

---

src/App.js

fix: makes sidebar full height in firefox

---

.circleci/config.yml
.travis.yml
test/e2e/puppeteer.js

Make circle errors go away on PRs.
License: MIT

Add circleci v2 config

---

.circleci/config.yml
.travis.yml
package-lock.json
package.json

See how a PR affects the final bundle size, right there in the PR checks view!
see: https://github.com/siddharthkp/bundlesize
License: MIT

chore: add bundlesize check and ci

---

package-lock.json
package.json
src/files/FilesPage.js
src/files/rename-prompt/RenamePrompt.js

feat: add rename prompt to file browser

---

src/files/rename-prompt/RenamePrompt.js

To comply with https://github.com/ipfs-shipyard/ipfs-webui/pull/689#issuecomment-401305713.
Added autofocus to the input as well.

fix: input focus

---

src/bundles/files.js
src/files/FilesPage.js

fix: navigation for encoded names

---

src/files/FilesPage.js
src/files/overlay/Overlay.js

feat: overlay component

---

src/bundles/files.js
src/bundles/ipfs.js
src/files/FilesPage.js
src/files/files-list/FilesList.js
src/files/selected-actions/SelectedActions.js

It allows you to download the files from the File Browser. Doesn't work with Companion yet though since it doesn't support `.config.get`.

feat: download files

---

package-lock.json
package.json
src/files/file-input/FileInput.js

💄: make dropdown look better

---

src/components/text-input-modal/TextInputModal.js
src/files/rename-modal/RenameModal.js

Do not allow empty names or the same name.

feat: validate renaming

---

src/files/files-list/FilesList.js

fix: utf8 characters on file names

---

package-lock.json
package.json
src/bundles/files.js

refactor: use pull streams to add files

---

src/files/FilesPage.js
src/files/file-input/FileInput.js
src/files/file-input/NewFolderModal.js
src/files/file/File.js

feat: new folder

---

src/files/file/File.js

fix: drag shadow

---

package-lock.json
package.json
src/bundles/peer-locations.test.js
src/files/share-modal/ShareModal.js

chore: mock indexedDB on tests

---

package-lock.json
package.json
src/bundles/routes.js
src/explore/LoadableExplorePage.js
src/files/LoadableFilesPage.js
src/peers/LoadablePeersPage.js
src/status/LoadableStatusPage.js

🚀: faster initial load times with loadable components

---

src/bundles/files.js
src/files/breadcrumbs/Breadcrumbs.js
src/files/file-preview/FilePreview.js
src/files/file/File.js
src/lib/files.js

Some File Browser Tweaks

---

src/index.js

One more step towards #749.
License: MIT

refactor: disable service worker

---

src/bundles/files.js
src/components/checkbox/Checkbox.css
src/files/file/File.js
src/files/files-list/FilesList.js

**Focused:**
**Some selected and a focused:**
**Selected and focused:**
Now you can also focus the upper directory so it's easier to navigate.
License: MIT

feat: files focus mode

---

package-lock.json
src/bundles/files.js
src/files/FilesPage.js
src/files/breadcrumbs/Breadcrumbs.js
src/files/file/File.js

From @olizilla (https://github.com/ipfs-shipyard/ipfs-webui/issues/748#issuecomment-414671819)
> Getting really good now! A couple of things from using the new fancy files:
> 
> - Now we've tightened up the file list, it feels like there is a little too much space at the top of the page. I don't have specific suggestions there, but what do you think?
> - The home icon with the underline seems a little to "strong" when we're at the root. It's all on it's own on the left and really dark and underlined, but it's not interesting until we start drilling down into the folders and files. Perhaps we should hide it or make it less visually distracting when we're at the root.
> - There are a few little gaps in the clickable areas on the file items. I keep managing to click right between the …

More files polishing

---

src/files/file-preview/FilePreview.js

feat: change can't preview message and add loading animation

---

src/status/PeerBandwidthTable.js
src/status/StatusPage.js

Also see #764 and #734
License: MIT

feat: prettier peers table

---

src/status/CountryChart.js
src/status/StatusPage.js

A pie chart showing the top 4 countries peers reside in.

[WIP] feat: peer country chart

---

package-lock.json
package.json
src/bundles/node-bandwidth-chart.js
src/bundles/node-bandwidth-chart.test.js
src/status/NodeBandwidthChart.js

I had to comment out the bandwidth simplifying because with it I would have a different number of points for .in and for .out. @alanshaw @olizilla any suggestions on this?
License: MIT

[WIP] feat: bandwidth chart polishing

---

package-lock.json
public/locales/en/status.json
src/status/NodeBandwidthChart.js
src/status/PeerBandwidthTable.js

💄: node bandwidth graph

---

src/components/text-input-modal/TextInputModal.js
src/files/share-modal/ShareModal.js
src/navigation/NavBar.js
src/welcome/WelcomePage.js

- Fixed inputs to have the same border-radius
- Fixed api address input focus to behave like the others:
| Before | After |
|--------|-------|
|![before](https://user-images.githubusercontent.com/33324750/46020682-db533d80-c0d6-11e8-8c00-7e8088334793.gif)|![after](https://user-images.githubusercontent.com/33324750/46020681-db533d80-c0d6-11e8-8e39-9bdf7b0ddd34.gif)|

fix: misc ui fixes

---

src/files/selected-actions/SelectedActions.js

Closes https://github.com/ipfs-shipyard/ipfs-webui/issues/820.

fix: enlarge on hover

---

src/bundles/files.js

Closes #826.
@alanshaw can you verify if it fixes the issue on your machine?

fix: sort folder by size

---

src/components/button/Button.js

Closes https://github.com/ipfs-shipyard/ipfs-webui/issues/822.

fix: btn disable state

---

package-lock.json
package.json

Closes #850.
Will merge this now until we find a cleaner solution.

fix: start and build scripts

---

public/locales/en/files.json
public/locales/en/welcome.json
src/components/about-ipfs/AboutIpfs.js
src/files/FilesPage.js
src/files/file-input/FileInput.js
src/files/files-list/FilesList.js
src/i18n.js
src/welcome/WelcomePage.js

See https://github.com/ipfs-shipyard/ipfs-webui/pull/847#issuecomment-427060102.

feat: add webui intro

---

public/locales/en/notify.json
src/bundles/notify.js
src/bundles/notify.test.js

Fixes https://github.com/ipfs-shipyard/ipfs-webui/issues/821.

fix: notify bundle

---

package-lock.json
package.json

- bundle as js-ipfs-api fix to allow file uploads > 15MB
WIP on #858 - large file uploads
License: MIT

chore: update to ipfs-redux-bundle@4.1.0

---

src/status/NodeInfo.js

Fixed speedometer colours and switched their order to match the chart. 
Fixes https://github.com/ipfs-shipyard/ipfs-webui/issues/876.

fix: speedometer colors

---

package-lock.json
package.json

Bump the multiaddr dep so we support the quic protocol in multiaddrs.
See:  #878

fix: support quic protocol in multiaddrs

---

docs/usability/notes/useabiltity-test-2018-12-03-portia-burton.md

@pkafei are you happy for me to add these notes to the repo?
License: MIT

docs: add useabilty test notes

---

docs/usability/notes/useabiltity-test-2018-12-03-teri-chadbourne.md

@terichadbourne please could you eyeball the notes from our usability test and let me know if you're happy for me to merge them?
This is a temporary repository while I collect more feedback. I'll be pulling the ideas that come out of them into issues on this repo.
License: MIT

docs: add useability test notes

---

docs/usability/notes/usability-test-2018-12-04-mhz.md

@meiqimichelle are you happy for me to merge in these rough notes from our usabiltiy test. I'll be replacing them with issues on the repo once I've done a round of interviews.
License: MIT

docs: add useabilty test notes from @meiqimichelle

---

package-lock.json
package.json
src/files/FilesPage.js
src/files/file-icon/FileIcon.js
src/files/file/File.js
src/files/files-list/FilesList.js
src/peers/PeersTable/PeersTable.js
src/peers/WorldMap/WorldMap.js
src/settings/SettingsPage.js

- max-width and center for files list and settings editor
- tweaks to files list to make the the filename clearer
- tweaks to the peers page to make the table responsive
cc @lanzafame 
License: MIT

fix: layout tweaks for the larger screen

---

package-lock.json
package.json

fix: update ipfs-geoip to fix geolocating of peers

---

package-lock.json
package.json

- Update ipfs-redux-bundle https://github.com/ipfs-shipyard/ipfs-redux-bundle/pull/24
Fixes https://github.com/ipfs-shipyard/ipfs-webui/issues/925
License: MIT

fix: no mixed content warnings on webui.ipfs.io

---

.circleci/config.yml

See: https://github.com/ipfs-shipyard/ipfs-dns-deploy

Simpler circle config

---

src/bundles/analytics.js

Just a rogue log.
License: MIT

chore: remove debug log

---

src/bundles/analytics.js

Ref.: https://github.com/ipfs-shipyard/ipfs-webui/issues/992

feat: use Desktop's countly key

---

package-lock.json
package.json
public/locales/cs/explore.json
public/locales/cs/files.json
public/locales/cs/status.json
public/locales/da/files.json
public/locales/da/status.json
public/locales/de/files.json
public/locales/de/status.json
public/locales/fr/files.json
public/locales/fr/status.json
public/locales/fr/welcome.json
public/locales/nl/files.json
public/locales/nl/status.json
public/locales/no/files.json
public/locales/no/status.json
public/locales/pt/files.json
public/locales/pt/peers.json
public/locales/pt/status.json
public/locales/sk/files.json
public/locales/sk/peers.json
public/locales/sk/status.json
public/locales/zh-CN/explore.json
public/locales/zh-CN/files.json
public/locales/zh-CN/peers.json
public/locales/zh-CN/status.json
public/locales/zh-CN/welcome.json
public/locales/zh-HK/peers.json
public/locales/zh-HK/welcome.json

- use countly app key from `window.ipfsDesktop` to allow it to pass in the test key during dev
- update the translations

Release 2.4.2

---

public/manifest.json

Fix manifest.json content

---

package-lock.json
package.json
src/App.js
src/bundles/files.js
src/bundles/files.test.js
src/files/file-input/FileInput.js
src/files/file/File.js
src/files/files-list/FilesList.js
src/lib/files.js
src/lib/files.test.js

Here are some basic tests for the functions `filesToStreams` and `doFilesWrite`. I also made a few changes so the files are already normalised when they get to `doFilesWrite`.

tests: filesToStreams and doFilesWrite

---

src/files/file-input/FileInput.js

fix: always close files dropdown

---

src/bundles/config-save.js
src/bundles/ipfs-desktop.js

See https://github.com/ipfs-shipyard/ipfs-desktop/pull/943.
License: MIT

feat: restart ipfs daemon after config change

---

src/bundles/analytics.js
src/bundles/config-save.js
src/bundles/ipfs-desktop.js

Closes https://github.com/ipfs-shipyard/ipfs-desktop/issues/944.
License: MIT

feat: use desktop version on Countly

---

src/settings/DesktopSettings.js

fix: use same font size and color on desktop settings

---

public/locales/de/explore.json
public/locales/en/explore.json
test/e2e/navigation.test.js

fix: revert em dash to hyphen 

---

package-lock.json
package.json
src/components/cid/Cid.js
src/components/cid/Cid.stories.js
src/components/identicon/Identicon.js
src/components/identicon/Identicon.stories.js
src/peers/PeersTable/PeersTable.js

Creating this PR for review after the peers table is updated.
This resolves #935
It currently can't be merged because of a change requested in that thread to move Peer Id to the first column and Location to the third. Let me know if I should roll back that change for an easier merge.
---
Rebased and resubmitting

feat: add peer identicons

---

src/files/files-list/FilesList.js

fix: drag'n'drop on MFS

---

src/components/overlay/Overlay.js

fix: modal backdrop

---

public/locales/fr/explore.json
public/locales/fr/files.json
public/locales/fr/peers.json
public/locales/fr/settings.json
public/locales/fr/status.json
public/locales/zh-CN/explore.json
public/locales/zh-CN/files.json
public/locales/zh-CN/peers.json
public/locales/zh-CN/settings.json
public/locales/zh-CN/status.json
public/locales/zh-CN/welcome.json

feat: update i18n

---

package-lock.json
package.json

chore: update redux bundler

---

package-lock.json
package.json
src/App.js

chore: update internal-nav-helper

---

src/bundles/index.js

fix: cache fn

---

package-lock.json
package.json
test/helpers/cid.js

chore: update multihashing async

---

src/settings/SettingsPage.js

fix: remove padding from experiments

---

public/locales/en/status.json
src/lib/tours.js

fix: step explore

---

README.md

Add BrowserStack info to grant our OSS licence ❤
I applied yesterday and we were accepted, you can find more [info on the website](https://www.browserstack.com/open-source).

add BrowserStack logo and info

---

src/peers/PeersTable/PeersTable.js

Fixes #1187. Shows full location when hovering over the location cell.
License: MIT

feat: show full location on hover

---

package-lock.json
package.json
src/bundles/config.js
src/explore/ExploreContainer.js

Close #1214. Also starts supporting multiple gateaway/api addresses.
License: MIT

feat: use local gateway on explore page

---

.circleci/config.yml

chore: force circle to run on tags

---

package-lock.json
package.json
src/status/NodeInfoAdvanced.js

Fixes the third issue mentioned [here](https://github.com/ipfs-shipyard/ipfs-redux-bundle/pull/28#pullrequestreview-310399308).
License: MIT

fix: allow non-multiaddress api url

---

src/bundles/peer-locations.js

Basically this was failing because I set it to "fail" if we couldn't determine the public IP and thus it wouldn't even check if the IP was private or not.
License: MIT

fix: local peers display

---

public/locales/en/explore.json

License: MIT
Signed-off-by: Luflosi <luflosi@luflosi.de>

fix: typos in node info paragraph

---

public/locales/en/status.json
public/locales/no/status.json

Fix misspelled "bandwith" in helptext
ref https://github.com/ipfs-shipyard/ipfs-webui/issues/1469

bandwith -> bandwidth

---

src/icons/Icons.stories.js

Allows:
- searching icons by text query
- changing the fill & stroke color
- changing the size of the icons
Direct benefits:
- found out problems with existing icons, like miss-configured viewbox and fill (will fix this in a PR soon)
- we can preview all the icons we're using 🎉 
Showcase: https://dl.dropboxusercontent.com/s/4se8lc2atpo36qf/cBPG7IhgSF.mp4

chore: add icons stories

---

src/icons/GlyphSmallArrow.js

Related with https://github.com/ipfs-shipyard/ipfs-css/issues/42

fix: small arrow fill

---

README.md

Ref https://github.com/ipfs-shipyard/ipfs-webui/issues/1420
Please fix my copy @jessicaschilling 🙏

chore: add docker section to readme

---

src/bundles/connected.js
src/components/connected/Connected.js
src/navigation/NavBar.js
src/status/NodeInfoAdvanced.js

- Fixes lidel's suggestions from https://github.com/ipfs-shipyard/ipfs-webui/pull/1577#pullrequestreview-464383699
- Fixes the "Status" tab item not being selected when using the icon: 
instead of

feat: improve ux in NodeInfo

---

src/bundles/peers.js
src/components/text-input-modal/TextInputModal.js
src/peers/AddConnection/AddConnection.js

Closes https://github.com/ipfs/ipfs-gui/issues/90

feat: add animation for add peer connection

---

src/files/FilesPage.js
src/files/download-file.js
src/lib/files.js

Closes https://github.com/ipfs-shipyard/ipfs-webui/issues/1576

fix: multiple item download with go-ipfs 0.5+

---

.circleci/config.yml

fix: correct _dnslink.dev.webui.ipfs.io

---

src/bundles/ipfs-desktop.js
src/files/file-input/FileInput.js

Fixes regression in folder import (https://github.com/ipfs-shipyard/ipfs-desktop/pull/1638#issuecomment-692051343)

fix: remove electron folder import code

---

src/files/FilesPage.js
src/files/context-menu/ContextMenu.js

Fixes https://github.com/ipfs-shipyard/ipfs-webui/issues/1631#issuecomment-692903563
- This was a regression on behavior compared to pre-breadcrumbs.

fix: context menu now has all options when it's a directory

---

package-lock.json
package.json

Ref: https://github.com/ipfs-shipyard/ipld-explorer-components/releases/tag/v1.6.1

chore: update ipld-explorer-components

---

src/bundles/files/actions.js

Fixed regression in files size
Closes https://github.com/ipfs/ipfs-webui/issues/1738

fix: files page size

---

public/locales/en/notify.json
src/bundles/notify.js
src/bundles/pinning.js
src/components/notify/Toast.js
src/files/modals/pinning-modal/PinningModal.js

Closes https://github.com/ipfs/ipfs-webui/issues/1751

feat: remote pin error feedback

---

src/files/FilesPage.js

fix: fix modal open when removing files

---

public/locales/en/app.json
src/components/api-address-form/ApiAddressForm.js

Closes #1807
>  ![Screenshot 2021-06-30 at 00-07-47 Settings IPFS](https://user-images.githubusercontent.com/157609/123873892-856eec80-d937-11eb-8cec-80b419e79356.png)

fix: add api input placeholder

---

public/locales/en/files.json
src/bundles/files/actions.js
src/files/FilesPage.js
src/files/modals/Modals.js
src/files/modals/add-by-path-modal/AddByPathModal.js

feat: "import from IPFS" with a name

---

public/locales/en/peers.json
src/bundles/peers.js
src/peers/AddConnection/AddConnection.js

Closes #1849.
@lidel I added the configuration change in the same bundle function as the swarm connect. Do you think it would be better to change to the config bundle?
Also, I noticed that when you change the config, if you go to the Settings page, the config isn't changed and you need to refresh. Somehow we need to trigger the config re-fetching here.

feat: add peer permanently by default

---

.github/workflows/ci.yml
package-lock.json
package.json
public/locales/en/explore.json
src/explore/ExploreContainer.js

Closes #1822 
Requires https://github.com/ipfs/ipld-explorer-components/pull/300
License: MIT

feat: support public and private gateway on IPLD explore

---

src/components/version-link/VersionLink.js

fix (versionLink): Missing ReleaseLink with Kubo IPFS implementation 

---

src/constants/pinning.js

* Add Filebase to List of Pinning Providers

feat: Add Filebase to List of Pinning Providers

---

src/constants/pinning.js

- feat: add Web3.Storage default pinning provider
- feat: add Estuary default pinning provider

feat: add Web3.Storage and Estuary to default pinning provider list

---

.github/workflows/test-e2e.yml
.github/workflows/test-storybook.yml
.github/workflows/test-unit.yml

fix https://github.com/ipfs/ipfs-webui/actions/runs/3176355571/jobs/5175558191

feat: add codecov_token to codecov step

---

.github/workflows/build.yml
.github/workflows/ci.yml
.github/workflows/test-e2e.yml

See https://github.com/ipfs/distributions/pull/1112

chore(ci): udpate artifact actions to v4

---

package-lock.json
package.json

Fixes https://github.com/ipfs/ipld-explorer-components/issues/465

fix: ipld-explorer-components@8.1.3
