ipfs/ipfs-webui

gulpfile.js
package.json

*In my previous pull request I forgot to commit and push some last minute changes I made, so currently the fix to allow the gulp server to proxy api requests forward to ipfs is not enabled, nor was it in the module version published to npm*
---
This is an enabled version.
I am however, not sure if this is going to stay in this package or how long this package is going to be alive as simple using many of the available proxy pass middleware solves both the issues.
I have found a simpler solution that should work, but does not due to a refereral header.
Using: https://www.npmjs.com/package/proxy-middleware
```
livereload: true,
middleware: function(connect, opts) {
var apiProxy = url.parse("http://127.0.0.1:5001/api")
apiProxy.route = "/api"
var ipfsProxy = …
```

Enabling API Proxy pass through

---

js/views/page.jsx

`window.location.port` will return `undefined` when no part is specified
on the url. This happens for port 80 as it's a default and not required.
This ends up with undefined being passed to the IPFS API, to which it
responds by using the default 5001.
This fixes #4

When the webui is running on port 80, it will not have an undefined port

---

Makefile

This fixes issue #11 to ensure that prior to doing a publish we have a clean build directory and we don't pull in any extra files.

Cleans the directory prior to a new building being published

---

js/pages/files.jsx
js/views/filelist.jsx
package.json

There are few fixes in this, mostly though this is to allow users to
unpin from the webui. This commit includes a version bump of the
`node-ipfs-api`, as well as passing in the recursive flag.
An unexpected addition to this commit is due to a change in `go-ipfs`
passing back an object of keys instead of an array.

Fixes #31, allowing unpinning via the webui

---

js/app.jsx
js/pages/bitswap.jsx
js/pages/config.jsx
js/pages/connections.jsx
js/pages/files.jsx
js/pages/globe.jsx
js/pages/home.jsx
js/pages/logs.jsx
js/pages/notfound.jsx
js/pages/objects.jsx
js/pages/routing.jsx
js/views/config.jsx
js/views/connection.jsx
js/views/connectionlist.jsx
js/views/copier.jsx
js/views/dhtgraph.jsx
js/views/editable.jsx
js/views/filelist.jsx
js/views/nav.jsx
js/views/object.jsx
js/views/page.jsx
js/views/peer.jsx
js/views/proptable.jsx
js/views/swarmvis.jsx
js/views/table.jsx
js/views/typography.jsx
package.json

Did the manual regression testing, everything checks out.

linting for jsx files

---

js/pages/files.jsx

This made the files page go from eating 100% cpu to idle.
I'd argue the relevant time you want to update these listings, is while adding files through the webui, and as this case is already covered without polling, i think we should just drop this line.
Cannot think of any usecase where you would want to have polling updates of pinned files at this point.
Maybe it does not fix #20 in its entirety, but it makes a huge difference in performance.

Remove polling interval from files view

---

byggfile.js

This (sometimes?) needs to be in the proxy for the api not to 403

rewrite referer to make api happy

---

less/bundle.less

Would still probably be better to keep the path at a flexbox-style maximum middle width. But this is better for now.

stop navbar flowing into to two lines

---

.eslintrc
app/scripts/app.js
app/scripts/include/globe.js
app/scripts/pages/config.js
app/scripts/pages/files.js
app/scripts/pages/routing.js
app/scripts/views/editable.js
app/scripts/views/filelist.js
app/scripts/views/globe.js
app/scripts/views/nodeprops.js
package.json

This is the setup for #151. The actual good logging messages still need to be written at a later point

feat: Replace console.log with debug

---

app/scripts/utils/localStorage.js

As noted by @diasdavid in https://github.com/ipfs/webui/pull/130#discussion_r48386312

Added a log

---

app/scripts/components/peers-viewer.js
test/components/peers-viewer.spec.js

https://github.com/ipfs/webui/issues/137

peers-viewer spec

---

app/scripts/views/page.js

Fixes a `TypeError: e.refs.dagPath.val is not a function` when clicking the GO button with a DagPath in the input box at the top of the webui.

Fix TypeError on call to input value

---

app/scripts/views/filelist.js

Fixes #512, makes delete button work, but UI feel is off; there's no responsiveness that the file was actually unpinned. I've added an alert() with a "please reload" message, but it's insufficient to call a solution.

Fixes #512, needs UI changes to feel better

---

src/app/js/components/ipfs.js
src/app/js/services/api.js

Fixes an issue mentioned in a comment for #95:
> There's also problems if you're trying to put HTTPS in front of the UI via nginx. It loads fine, but then the web-ui immediately tries to access it's own content via HTTP rather then HTTPS and is blocked.

Make the API accessible from the default HTTPS port

---

src/app/js/views/filelist.js

the _unpin method expects params (hash, event). Calling the method with  this._unpin(event, file.id) will cause an error.

swap params in _unpin method

---

src/app/js/components/ipfs.js

Hey,
I saw that when NODE_ENV is set to production, even if the site is on https, the call is made over http. Thsi PR fixes it, taking the protocol of the site to send the requests.
See #625

Add HTTPS when calling ipfs API

---

README.md

The ordered list in "Release a new version of the WebUI." is currently an ordered list within an unordered list. This moves the ordered list of steps to the top-level in the README.

style: mv nested ordered list to top level

---

package-lock.json
src/components/button/Button.css
src/components/button/Button.js
src/components/button/Button.stories.js
src/components/file/File.stories.js
src/index.css

Adds a nice button component with customisable colors and a disabled flavour. Use tachyons for the majority of the styles and adds a Button.css file for interactive flourishes.
Fixes lint errors on File component.
License: MIT

feat: add button component and storybook

---

.editorconfig
.gitattributes

Adds editorconfig to keep our editors ending lines with LF and .gitattributes to get git to ensure LF line endings when the editor doesn't.
License: MIT

chore: ensure consistent line endings

---

src/js/components/ipfs.js
src/js/services/api.js

I fix and test the use of https related to the pull request #639 and the issue #611

Fix support for use behind https

---

package-lock.json
src/files/FilesPage.js
src/files/files-list/FilesList.js
src/index.css

The commits on this PR are self contained and should be merged without squashing.

feat: add delete prompt to file browser

---

src/bundles/files.js
src/files/FilesPage.js
src/files/file/File.js
src/files/files-list/FilesList.js

Closes #694.
It also changes a bit the Redux files bundle so we can start to handle eventual errors that might happen and show them to the user (will do in another PR).

fix: issues when multiple files on the same dir have the same hash

---

package-lock.json
package.json
src/bundles/files.js
src/files/FilesPage.js
src/files/file-input/FileInput.js
src/files/files-list/FilesList.js
src/lib/path.js

feat: add folder

---

src/files/FilesPage.js

Fixes the error that happened when the user tried to navigate on the file browser with items selected.

fix: error when moving page if items were selected

---

src/files/file/File.js

Truncates the text when it overflows and adds a tooltip on hover.

feat: truncate text and add tooltip on hover

---

src/bundles/files.js
src/files/FilesPage.js
src/files/share-modal/ShareModal.js
src/lib/files.js

When you hit share, you'll get a modal like this:
When @fsdiogo has the new sharing/downloading page finished, we can change it to something like `https://share.ipfs.io/#QmHash`.

feat: share files link

---

src/components/overlay/Overlay.js
src/files/files-list/FilesList.js

This introduces the following shortcuts:
- ESC - Unselect everything.
- F2 - Rename selected.
- Del - Delete selected.
- Enter or Meta+Arrow Right - Open selected.
- Arrow up/down - Focus files.
@olizilla I see an issue here I can't find a way to solve right one: if we have a modal opened, we don't want this shortcuts to trigger. I'm just unsure of how to know if a modal is opened. There are some that are completely independent and I would need to make their components fully controlled which would require a lot of changes. There must be a simpler way to handle this.

feat: arrow navigation

---

src/bundles/files.js
src/files/files-list/FilesList.js
src/lib/dnd-backend.js
src/lib/files.js

@lidel with your comment yesterday (https://github.com/ipfs-shipyard/ipfs-webui/issues/762#issuecomment-416643973) I ended up changing the code and simplifying it a bit.
Although, it happened once or twice to upload like 10 streams and it would only return 1 hash which I think it might be related to https://github.com/ipfs/js-ipfs-api/issues/797!
It also happened before, but since it was only one by one, they wouldn't all fail.
License: MIT

refactor: simplify file adding

---

src/files/file-preview/FilePreview.js

If something goes wrong, we should try providing the next action user can pick.
In case of being unable to see the preview, people will appreciate an option of direct download without the need for going back to file list.
This PR adds a plain text link, but the UI can be improved in separate PRs:

feat: suggest download when preview not possible

---

src/status/NodeBandwidthChart.js

The bandwidth graph now has the minimum range set to 0 - 1 Mb/s.
License: MIT

feat: start bandwidth graph at 1 Mb/s

---

README.md

@lidel I stole some of your words on https://github.com/ipfs-shipyard/ipfs-webui/pull/772!
Could you take a look and add/update anything if you feel to?

docs: i18n

---

README.md
cors-config.sh

- bring back `quick-config.sh` but as `cors-config.sh` to explain what it does.
- clarify the cors config from the readme, and recommend `cors-config.sh` first.
wip on #817 
License: MIT

docs: cors-config.sh and improve cors config docs

---

src/files/file-input/ByPathModal.js

Adds the ability to `add by path` with only the CID. Also works with `/ipfs/` prefixed.
Closes https://github.com/ipfs-shipyard/ipfs-webui/issues/824.

fix: add by path

---

public/locales/en/status.json
src/App.js
src/components/footer/Footer.js
src/components/footer/Footer.stories.js
src/navigation/NavBar.js
src/status/NodeInfo.js
src/status/StatusPage.js

Add a footer on the status page with links to the repo and bug reporing.
Only add it on the stats page as it looks weird during page load on the
other pages... it needs more design consideration before we roll it out
across all of them.
This isn't using our shared component library yet, but it can in the future.
There is a discussion to be had about whether components should decide
the namespace to use or if they should be agnostic to where the keys come
from, and let the page decide. The component library proposal suggested
we let the component decide, but it felt more natural to let the page decide
and wire it in. This would let us consolidate keys into fewer resources which
would be nice for translators (a couple of keys in lots and lots of resources
is awkward) and http requests (each …

feat: add footer with code and bugs links

---

package-lock.json
package.json
src/bundles/connected.js
src/bundles/identity.js
src/bundles/index.js
src/components/provider-link/ProviderLink.js
src/status/NodeInfo.js
test/e2e/navigation.test.js

**blocked on**
Web UI wants all the privileges. With window.ipfs the files view
gets silo'd to the files added _in this origin_ so it's gonna
cause confusion.
This PR updates thing to use the new ipfs-redux-bundle and skips
window.ipfs in the provider checks.
Also adds an identity bundle as we no longer use /id as the
ipfs connection test, to move us towards supporting the read-only
api where it is all that is available.
fixes #787 
fixes #837 
License: MIT

fix: skip window.ipfs

---

package.json
public/index.html
public/locales/en/status.json
src/navigation/NavBar.js
src/navigation/Navbar.css

Adds the git revision.
In a meta tag:
In the UI:
Closes https://github.com/ipfs-shipyard/ipfs-webui/issues/842.

feat: add git revision

---

package-lock.json
package.json

This PR bumps version of `cids` dependency from v0.5.3 to v0.5.5.
That is all.
It took me some time to figure it out, but the short story is:
There are known issues with [cids](https://github.com/ipld/js-cid) library v0.5.3:
- the way `isCID` works changed in [v0.5.4](https://github.com/ipld/js-cid/releases/tag/v0.5.4) (aka "THE BREAKING CHANGE")
- `toV0` and `toV1` created instances that made `isCID` return `false` (aka "oops", fixed in [v0.5.5](https://github.com/ipld/js-cid/releases/tag/v0.5.5))
The problem does not manifest when Web UI runs in standalone mode and uses ipfs-api bundled with itself, but when it runs against IPFS API  instance exposed by ipfs-companion the discrepancy between different cids implementations produce `Error: invalid argument` as seen below:
| Web UI using …

fix: isCID in ipfs-companion context

---

src/App.js
src/bundles/navbar.js
src/files/FilesPage.js
src/files/files-list/FilesList.js
src/navigation/NavBar.js

This is a minimal implementation of a responsive nav as part of #871 
We can go fancier in the future, but this is a minimal change to behave reasonably on small screens.
On small screens, the navbar has a horizontal scroll, so you can swipe across to see the other nav items.

feat: responsive nav

---

README.md
cors-config.sh
src/welcome/WelcomePage.js

AFAIK Web UI does not need this, and we should not ask people to set it  if they don't really need it. 
See also:
- Potential problem with  `Access-Control-Allow-Credentials`: https://github.com/ipfs/go-ipfs/issues/5745
- HTTP Headers Cleanup: https://github.com/ipfs/in-web-browsers/issues/132

docs: remove CORS Credentials header

---

package-lock.json
public/locales/en/settings.json
src/bundles/index.js
src/bundles/ipfs-desktop.js
src/settings/DesktopSettings.js
src/settings/SettingsPage.js
src/settings/SettingsPage.stories.js
src/settings/Title.js
test/e2e/navigation.test.js

More info see: https://github.com/ipfs-shipyard/ipfs-desktop/issues/674.
IPFS Desktop injects a bundle on `window.ipfsDesktop`. If it's present, we show IPFS Desktop specific settings.
(Screenshot taken with IPFS Desktop)
License: MIT

feat: IPFS Desktop settings

---

public/locales/en/files.json

This PR fixes issue reported  by @Magik6k via https://www.transifex.com/ipfs/ipfs-webui/:
>  ![2018-11-17--19-08-27](https://user-images.githubusercontent.com/157609/48664257-30d71580-ea9c-11e8-9a17-6968d0188193.png)
Preview:
> ![2018-11-17--19-21-10](https://user-images.githubusercontent.com/157609/48664412-857b9000-ea9e-11e8-85ff-3348cbb6f0c7.png)

fix: add missing quotes on Files screen

---

package-lock.json
package.json

Remove malicious code as per https://github.com/dominictarr/event-stream/issues/116
`event-stream>3.3.4`  is the problem.
**before**
```console
$ npm ls event-stream flatmap-stream
ipfs-webui@2.2.0 /Users/oli/Code/ipfs-shipyard/ipfs-webui
└─┬ npm-run-all@4.1.3
└─┬ ps-tree@1.1.0
└─┬ event-stream@3.3.6
└── flatmap-stream@0.1.2
```
**after**
```console
$ npm ls event-stream flatmap-stream
ipfs-webui@2.2.0 /Users/oli/Code/ipfs-shipyard/ipfs-webui
└── (empty)
```
License: MIT

fix: remove event-stream from dev deps

---

src/files/files-list/FilesList.js

Use the keyup rather than keydown. keydown has always been weird.
fixes #889
License: MIT

Fix spacebar file select ff

---

public/locales/en/status.json
src/bundles/index.js
src/bundles/peer-locations.js
src/bundles/peer-locations.test.js
src/bundles/peers.js
src/bundles/repo-stats.js
src/components/box/Box.js
src/components/definition/Definition.js
src/components/details/Details.js
src/components/shell/Shell.js
src/status/NetworkTraffic.js
src/status/NodeInfo.js
src/status/NodeInfoAdvanced.js
src/status/StatusConnected.js
src/status/StatusConnected.stories.js
src/status/StatusHeader.js
src/status/StatusNotConnected.js
src/status/StatusNotConnected.stories.js
src/status/StatusPage.js
src/welcome/WelcomePage.js

wip on #887 to dial down geolocation activity
License: MIT

replace distribution chart with better node stats

---

src/welcome/WelcomePage.js

Adds the default Web UI origin (`http://127.0.0.1:5001`) and doesn't show duplicate configs.
Fixes https://github.com/ipfs-shipyard/ipfs-webui/issues/892.

fix: dedupe cors config

---

src/peers/PeersTable/PeersTable.js
src/peers/WorldMap/WorldMap.js

- Make make peer country names more legible. 
- Make peer map more responsive, within sensible bounds.
fixes #880 
fixes #903 
| 3840x2160 | 1440x900  | 411x731 pixel-2
|-------------|------------|------------------
| <img width="784" alt="screenshot 2018-12-13 at 12 42 02" src="https://user-images.githubusercontent.com/58871/49939703-750bd900-fed5-11e8-9a4b-458e0d0947d4.png"> | <img width="793" alt="screenshot 2018-12-13 at 12 43 08" src="https://user-images.githubusercontent.com/58871/49939739-9076e400-fed5-11e8-9540-2e287119515e.png"> | <img width="292" alt="screenshot 2018-12-13 at 12 43 45" src="https://user-images.githubusercontent.com/58871/49939783-abe1ef00-fed5-11e8-90ca-11d86fbf83d0.png">
License: MIT

fix: responsive peers map. larger country flags

---

public/locales/en/notify.json
src/bundles/files.js
src/bundles/notify.js

Adding a folder was failing because of the length of the api response. It would also fail and give an incoherent error if adding a folder with an existing folder name. 
Fixes https://github.com/ipfs-shipyard/ipfs-webui/issues/922.

fix: add folder

---

package-lock.json
package.json

Fixes #932 by updating the `multiaddress-to-uri` dependency.
Please check https://github.com/tableflip/multiaddr-to-uri/pull/3.
License: MIT

fix: show IPv6 URIs correctly

---

package-lock.json
package.json
src/files/context-menu/ContextMenu.js
src/files/context-menu/ContextMenu.stories.js
src/files/dropdown/Dropdown.js
src/files/file/File.js

The ContextMenu was a standalone component but to add the ability to be opened by right-clicking a file I had to refactor it a bit and couple its logic to the File component.
Right-clicking a file now opens the context menu, but always in the default position. I've tried to open it where the user clicked but that was taking a lot of time and I don't see this as a priority right now.
Closes https://github.com/ipfs-shipyard/ipfs-webui/issues/917.

chore: open ContextMenu on right-click

---

src/components/checkbox/Checkbox.css
src/files/selected-actions/SelectedActions.js

This PR addresses small UI improvements:
* Removed the box shadow from the checkboxes; as the app is mostly flat the checkboxes looked a bit off
| Before | After |
| ------ | ----- |
| <img width="429" alt="cb-before" src="https://user-images.githubusercontent.com/33324750/52218416-85678100-2892-11e9-9314-91882cbc97c8.png"> | <img width="432" alt="cb-after" src="https://user-images.githubusercontent.com/33324750/52218436-8dbfbc00-2892-11e9-828f-c58fab738486.png"> |
* Fixed the selected actions spacing to match the header spacing;
* Fixed font sizes and colours
| Before | After |
| ------ | ----- |
| <img width="1142" alt="sa-before" src="https://user-images.githubusercontent.com/33324750/52218730-2bb38680-2893-11e9-9664-4cb4f09049aa.png"> | <img width="1144" alt="sa-after" …

chore: update selected actions ui

---

public/locales/en/files.json
src/files/FilesPage.js
src/files/file-input/FileInput.js
src/files/new-folder-modal/NewFolderModal.js
src/files/rename-modal/RenameModal.js

As per https://github.com/ipfs-shipyard/ipfs-webui/issues/915#issuecomment-452768683, I've refactored the add dropdown. Heavily inspired by Drive and Dropbox.
- Separate the `create new folder` from the `add to ipfs` dropdown. This way, everything inside that dropdow is to add file/folder/cid to our repo.
- Renamed the dropdown to just `+ Add`. Previously we had `+ Add to IPFS`, which is not 100% correct. This let me update the `Add by path` which was super confusing, to `Add from IPFS`, which I think is more clear because it tells you you're adding something that is already on IPFS. 
Closes https://github.com/ipfs-shipyard/ipfs-webui/issues/915.

chore: update add dropdown

---

src/components/loading-animation/LoadingAnimation.css
src/components/loading-animation/LoadingAnimation.js
src/files/files-list/FilesList.css
src/files/files-list/FilesList.js

Adds a loading animation when changing folders because some requests can hang for a bit and there was no clear indication that something was going on.
When you click on a folder, the files list gets an opacity and I went for something like the youtube cards animation, but keeping the content visible: 
Fixes https://github.com/ipfs-shipyard/ipfs-webui/issues/926.

feat: add loading animation for files resp

---

public/locales/en/files.json
src/components/text-input-modal/TextInputModal.js
src/files/file-input/ByPathModal.js

Clarifies what `Add From IPFS` modal does:

chore: add example to addFromIpfs modal

---

src/files/context-menu/ContextMenu.js
src/files/file/File.js
src/files/files-list/FilesList.js

Until this point every `<File>` component had a `<ContextMenu>` component inside. I've extracted the ContextMenu out, so now a `<File>` only has placeholder dots and calls one `<ContextMenu>` that is shared by all files and can be found on the `<FilesList>`. This should help the performance of the app as it cuts a huge amount of DOM nodes.

chore: extract ContextMenu from each file

---

src/files/file/File.js
src/files/files-list/FilesList.js

After the `<ContextMenu>` refactor in https://github.com/ipfs-shipyard/ipfs-webui/pull/956 some known SVG rendering issues in Firefox reappeared. This PR fixes that.

fix: firefox svg render

---

README.md
docs/LOCALIZATION.md
public/locales/README.md

Adds a `public/locales/README.md` as a notice to intrepid localizers that Transifex is the prefered way. Moves the technical details for developers into `docs/LOCALIZATION.md`
Seperate to this PR, i've also added issue templates, with a specific one about translation to make it extra obvious.
Fixes #954

Add notice for contributors about Transifex process

---

.circleci/config.yml

see: https://github.com/ipfs-shipyard/ipfs-webui/pull/965#pullrequestreview-206605757
License: MIT

fix: tweak cluster params for ci build

---

src/bundles/index.js
test/e2e/navigation.test.js

- fixes issue where a readonly api would fool us into thinking we have a full api. If you look at https://webui.ipfs.io right now, you'll find it can't find your local ipfs daemon, as it finds the one provided by the domain first.
License: MIT

fix: ensure we have a full api available

---

src/bundles/config.js

Fixes #966 by not printing the error. That's an expected error in that function. We could also make the function receive an `expectsFailure` boolean variable which would tell whether or not to print the error.
License: MIT

fix: don't print out expected error

---

src/bundles/analytics.js
src/bundles/analytics.test.js

I think this deserves a proper refactor instead of a hotfix like this one.

fix: make analytics opt-in

---

src/bundles/files.js
src/lib/sort.js

Fixes https://github.com/ipfs-shipyard/ipfs-webui/issues/975.

fix: use localeCompare to sort files

---

.gitignore
.vscode/settings.json
package-lock.json
package.json
public/locales/en/notify.json
public/locales/en/peers.json
src/bundles/notify.js
src/bundles/peers.js
src/peers/AddConnection/AddConnection.js
src/peers/PeersPage.js

Closes #891.
As a first iteration this is what I've done:
It works, but we don't provide feedback if it worked or not. What do you think?
/cc @lidel @olizilla @fsdiogo

feat: add connection

---

.circleci/config.yml
src/bundles/analytics.js

The analytics upgrade switched around the regex logic for identifying
action types. The FILES_WRITE_UPDATED action passes the first regex
but doesn't pass the async state regex, which we then exec, which throws.
This is fixed by testing for both before exec-ing.
License: MIT

fix: file add error

---

package-lock.json
package.json
src/App.js
src/bundles/files.js
src/files/file/File.js
src/files/files-list/FilesList.js
src/lib/dnd-backend.js
src/lib/files.js

- replace our directory walking code with https://github.com/grabantot/datatransfer-files-promise#readme
- normalise the logic so adding via fileinput and drop both go
through the filesToStreams logic.
License: MIT

fix: get drop dir working again

---

src/App.js

if you drop files inside dirs that have zero or fewer items than
fills the vertical height, the drop would land on the app rather
than the file list, which would cause files dropped inside the dir
to be added at the root rather than the dir.
This PR is a quick fix to ensure the drops handled at the app level
add the files to the current dir where we are on the files page.
| Before | After |
|--------|------|
| ![webui-drop-on-empty-dir-before](https://user-images.githubusercontent.com/58871/56651668-7ddd9a00-6681-11e9-93da-8b468ff4c370.gif) | ![webui-drop-on-empty-dir-after](https://user-images.githubusercontent.com/58871/56651677-8635d500-6681-11e9-8ad8-902c37a49a52.gif)
License: MIT

fix: handle file-drop inside empty dir

---

src/files/FilesPage.js
src/files/file-input/FileInput.js
src/peers/AddConnection/AddConnection.js

Make the add buttons bg-navy and highligh the plus symbol in aquaish
WIP on #1004
License: MIT

fix: improve color contrast on buttons

---

src/navigation/NavBar.js

As per https://github.com/ipfs-shipyard/ipfs-webui/issues/1004.
Update the way a link is active in the navbar:

chore: update navbar active item

---

public/locales/en/settings.json
src/App.js
src/bundles/redirects.js
src/navigation/NavBar.js
src/settings/SettingsPage.js
test/e2e/navigation.test.js

This closes #1019 by allowing the Settings page even when IPFS config is not available, or the daemon is offline. It might be useful because the settings page contains much more than IPFS own settings.
License: MIT

feat: allow settings even when the daemon is offline

---

public/locales/en/settings.json
src/settings/DesktopSettings.js

https://github.com/ipfs-shipyard/ipfs-desktop/pull/906
License: MIT

feat: add ipfs on path option

---

public/locales/en/files.json
src/bundles/files.js
src/files/FilesPage.js
src/files/file-preview/FilePreview.js

Removes the "pending" TODO on files bundle, by adding three properties to the main object and using it instead.
License: MIT

refactor: cleans up files.extra on preview

---

src/bundles/files.js
src/files/FilesPage.js

Fixes the useless _tons_ of re-renders on file pages. It happened because every time we returned from `selectFiles`, we were sorting at the time and using the spread operator, hence creating a new _different_  object, causing a re-render. Now it just changes when the files are fetched _and_ when the sorting is updated.
Also, fixed the issue where you open the Web UI on files page and it just wouldn't load.
License: MIT

fix: useless list re-renders

---

package-lock.json
package.json
public/locales/en/files.json
src/bundles/files.js
src/files/FilesPage.js
src/files/context-menu/ContextMenu.js
src/files/file-preview/FilePreview.js
src/files/files-list/FilesList.js
src/files/header/Header.js
src/files/info-boxes/AddFilesInfo.js
src/files/info-boxes/CompanionInfo.js
src/files/info-boxes/WelcomeInfo.js
src/files/modals/Modals.js
src/files/modals/delete-modal/DeleteModal.js
src/files/modals/delete-modal/DeleteModal.stories.js
src/files/modals/new-folder-modal/NewFolderModal.js
src/files/modals/rename-modal/RenameModal.js
src/files/modals/rename-modal/RenameModal.stories.js
src/files/modals/share-modal/ShareModal.js
src/files/modals/share-modal/ShareModal.stories.js

This declutters the `FilesPage` file a lot.
- Moves the modals to their own directory and the info boxes to their own directory too 5409447
- Cleans up files.extra on preview c2055cc
- Quickly fixes a message f8a3059
- Cleans up context menu 63b4164
- Moves header outside of files page ea6b761
License: MIT

refactor: cleanup files page

---

package-lock.json
package.json
src/bundles/files.js

Update ipfs-redux-bundle to ensure latest ipfs-http-client is used
with fix for https://github.com/ipfs/js-ipfs-http-client/issues/967
License: MIT

fix: file upload error in http client

---

package-lock.json
package.json
src/lib/dnd-backend.js
src/lib/dnd-backend.test.js

Fixes #1045 by using my [fork](https://github.com/hacdias/datatransfer-files-promise) of `datatransfer-files-promise`. I didn't publish it because I was hoping the original creator would accept my PR, although @grabantot doesn't seem very active on GitHub.
License: MIT

fix: drop multiple files on chrome

---

package-lock.json
package.json
src/lib/dnd-backend.js

The PR to the original `datatransfer-files-promise` was merged (https://github.com/grabantot/datatransfer-files-promise/pull/3), so this reverts to the original package.
License: MIT

chore: use original datatransfer-files-promise

---

src/bundles/peer-locations.js
src/lib/sort.js
src/peers/PeersTable/PeersTable.js

Rebased for master.
Sorting in peer table with default sorting based on latency column

chore: add sorting to peers table

---

public/locales/en/settings.json
src/settings/SettingsPage.js

Closes #1110. The button also has a hovering title saying 'IPFS Config Help'.
License: MIT
/cc @autonome
@autonome I can't set you as a reviewer... probably we need to give you permission somewhere. @olizilla do you know anything about this?

feat: add ipfs config help link

---

public/locales/en/files.json
src/bundles/files/actions.js
src/files/FilesPage.js
src/files/context-menu/ContextMenu.js
src/files/file-icon/FileIcon.js
src/files/files-list/FilesList.js
src/files/header/Header.js

Closes #1095.
Clicking on the item goes to to the explore section:
It has less ctx menu opts:
If the user tries to navigate to it anyway (though the URL or sth):

fix: non unixfs on files

---

src/bundles/peer-locations.js
src/bundles/peers.js
src/peers/PeersTable/PeersTable.js

In response to #1072 I've done the following:
I also made the following minor changes:
- Remove sorting notes column
- Simplified latency sorting (removed `rawLatency`)
---
The last item mentioned in #1072 is checking performance with a large number of peers. Any suggestions about the best way to test that?

chore: Peer page sorting adjustments

---

src/bundles/files/actions.js

This PR makes pin listing more robust by never throwing errors returned by
`ipfs.files.stat` for individual pins. Fixes https://github.com/ipfs-shipyard/ipfs-webui/issues/1095 for all repos.
Error handling introduced in #1115 was bit naive and when anything other than 'non unixfs' error was detected, it was re-thrown. This broke rendering of pin list on my end:
> ![](https://user-images.githubusercontent.com/157609/62941627-ce1a6c80-bdd6-11e9-9976-3f2f7425dbc3.png)
My repo has some bizzare DAGs, which provided good sandbox for testing shortcomings of old error handling:
> ![unhandled-errors-2019-08-20--16-32-16](https://user-images.githubusercontent.com/157609/63359843-b78f8a80-c36d-11e9-8854-7d588e13d318.png)
We just mark non-unixfs or errored items as 'unknown' and continue.
That way …

fix: stop crashing pin screen on a single ipfs.files.stat error

---

public/locales/en/files.json
public/locales/en/status.json
src/App.js
src/bundles/files/actions.js
src/files/explore-form/FilesExploreForm.css
src/files/explore-form/FilesExploreForm.js
src/files/explore-form/FilesExploreForm.stories.js
src/lib/tours.js

Close #1109. Closes #1112. #1027 introduced a regression: we replaced the IPLD explore bar by the files Explore bar. Although, we didn't put the IPLD explore bar anywhere else.
This PR makes the top bar work for both Files and IPLD sections. How? Like this:
License: MIT

feat: add inspect near browse

---

src/bundles/files/actions.js
src/bundles/files/consts.js
src/bundles/files/index.js
src/bundles/files/selectors.js
src/files/FilesPage.js
src/files/header/Header.js

This applies #1122!
Is it better with one or zero decimals?
I believe that using 0 decimals can hide a bit the difference between repo and the files sizing... 
License: MIT

feat: improve nav bar

---

src/App.js

Increases the draggable area of IPFS Desktop. The new draggable area is (anywhere in the light blue area can be clicked to drag and move the window around):
- Please see https://github.com/ipfs-shipyard/ipfs-desktop/pull/1071

fix: draggable area on desktop

---

src/files/explore-form/FilesExploreForm.js

Fixes #1144.
Due to HTML rules, the first button in the tree is considered to be the default one. It was the Inspect one.
We had an `onSubmit` function that should be triggered on the form submit, although that was not working.
I changed the form to a simple div, listen to enters on input and each button has its own click listener.
And now, Browse button is the default one!
License: MIT

fix: browse is now the default button

---

src/bundles/peer-locations.js
src/peers/PeersTable/PeersTable.js

Fixes #1141 by showing the full address on hover:
License: MIT

feat: show full address on connectivity hover

---

src/bundles/peer-locations.js

Fixes #1141. Shows all protocols in the connectivity column. **This is an alternative for #1166. Only one must be merged.**
License: MIT

feat: show all protocols in connectivity

---

src/components/address/Address.js

Fixes #1160. Shifts the highlight of `/p2p-circuit` addresses to the right, highlighting the IP address and the port.
I noticed there are some addresses that don't contain IP address, nor port. Should we perhaps disable the highlight on those? If so, that should be a different PR though.
License: MIT

fix: correctly highlight p2p-circuit addresses

---

src/components/address/Address.js

I also added `ipfs` to the list of protocols to make sure we don't highlight it.
License: MIT

feat: highlight everything but protocols

---

.circleci/config.yml
README.md

@olizilla as far as I understood, all subdomains from `ipfs.io` are pinned to the gateway. This adds a `dev.webui.ipfs.io` subdomain for the latest commit and changes the current `webui.ipfs.io` to the latest **released version** and not commit.
On tags, we update **both** domains DNSLinks, otherwise we just update the development website.
Please let me know if there is anything else that should be done to enable the domain `dev.webui.ipfs.io`. I believe someone should set some CNAME or something like that.
Ref.: This blocks further progress on fixing IPFS Desktop CI issues: https://github.com/ipfs-shipyard/ipfs-desktop/issues/1055.
License: MIT

chore: add dev.webui.ipfs.io

---

src/files/modals/Modals.js

Fixes #1215. The rename modal was getting updated when passing an `undefined`/`null` modal to show. At that time, it would tell the modals to show up, which was reusing the previous data.

fix: rename modal keeping the previous name

---

src/bundles/peer-locations.js
src/peers/WorldMap/WorldMap.js

This is related to #1072. Now we only show one dot per city. This can still be improved because there are still re-renderings being done even though the list keeps the same coordinates.

improvement: one dot per city

---

src/App.js

Vendor-specific properties must start with an uppercase letter.
License: MIT

fix: WebkitAppRegion is uppercase

---

src/settings/DesktopSettings.js

Disables launch on startup on OSes that are not Windows, macOS or Linux.
License: MIT

fix: disable launch on startup on unsupported platforms

---

src/peers/WorldMap/WorldMap.js

- change colors as suggested in https://github.com/ipfs-shipyard/ipfs-webui/issues/1277#issuecomment-546060437
- disable text selection (makes peer count feel like a part of the map)
closes #1277

fix: peer count contrast on Peers screen

---

src/bundles/peer-locations.js
src/bundles/peer-locations.test.js

Closes #1287 by checking if `addr.address` is an actual IP.
License: MIT

fix: peers page with /p2p-websocket-star addrs

---

src/components/about-ipfs/AboutIpfs.js

fix: remove typo in 'IPFS is a web' description on Files screen

---

package-lock.json
package.json
src/bundles/peer-locations.js
src/bundles/peer-locations.test.js

fix: geoip and peers on map

---

src/navigation/NavBar.js

This allows to scroll the navbar when your window is not tall enough to display the entire length.

Allow vertical scroll in the navbar

---

README.md
cors-config.sh
package-lock.json
package.json
patches/ipfs-http-client+39.0.2.patch
src/welcome/WelcomePage.js

https://github.com/ipfs/go-ipfs/pull/7097 will block `GET` commands on API port, requiring everything to be a POST request.
This breaks _Files_ screen in ipfs-webui as noted in https://github.com/ipfs-shipyard/ipfs-webui/issues/1429
ipfs-webui is using older version of js-ipfs-http-client, one before huge refactor into async iterables, which means switching to the latest version won't be a trivial task, as  the amount of code and dependencies that needs to be refactored is unknown.
Due to time constraint I made a decision to patch it in npm `postinstall` so we can release this ASAP and ship with go-ipfs 0.5.
`postinstall` script will apply a simple patch on top of ipfs-http-client v39.0.2 to ensure it sends commands as POST
Proper fix will land when ipfs-webui is refactored to work with …

fix: support POST-only HTTP API

---

package-lock.json
src/files/file-preview/FilePreview.css
src/files/file-preview/FilePreview.js

- Makes PDF viewer height take up full screen height per #1434 
- Unfortunately can't be based entirely on Tachyons references since fixed pixel heights for assorted header items
- Side note: something similar may be happening in https://github.com/ipfs-shipyard/ipld-explorer/issues/53
closes #1434

Variable viewer height

---

public/locales/en/settings.json
src/bundles/ipfs-desktop.js
src/settings/DesktopSettings.js

See https://github.com/ipfs-shipyard/ipfs-desktop/issues/1290.
License: MIT

fix: start on login

---

public/locales/en/app.json
public/locales/en/files.json
public/locales/en/peers.json
public/locales/en/settings.json
public/locales/en/status.json
src/App.js
src/files/FilesPage.js
src/helpers/i8n.js
src/lib/tours.js
src/peers/PeersPage.js
src/settings/SettingsPage.js
src/status/StatusPage.js

Fixes #1439
A future improved solution would be to re-use all the repeated translations, but the current architecture doesn't allow it.

fix: translated tour guides for all pages

---

src/bundles/files/actions.js
src/bundles/files/utils.js

`infoFromPath` decodes the given path. If the path is already decoded, it will be re-decoded and breaks MFS paths like `/dapps/http/127.0.0.1%3A8080/ipns` (IPFS companion creates this).
This problem can be reproduced by running:
```
ipfs files mkdir /%3A/foo -p
```
and then visit `#/files/%253A/foo` in Web UI. (It says "Failed to get those files.")
This PR fixes the problem by not decoding the path that is already decoded.

fix(files): do not double-decode paths in infoFromPath

---

src/bundles/files/actions.js

Possible fix for #1367
- Drag n dropping outside the "files" area would result in the error reported in the issue. However, drag n dropping in the "files" would work just fine with the same file. After some investigation, the `root` property appears to be undefined when dragging outside the zone 🤷

fix: drag n drop now works if outside the file area

---

public/locales/en/explore.json
public/locales/en/files.json
public/locales/en/peers.json
public/locales/en/status.json
public/locales/no/status.json

- Closes #1460: grammar error in helptext
- Closes #1461: Continue to learn more -> Click "Next" to learn more

Miscellaneous help text fixes

---

package-lock.json
package.json
src/components/button/Button.js
src/components/connected/Connected.js
src/components/language-selector/language-modal/LanguageModal.js
src/components/text-input-modal/TextInputModal.js
src/components/tour/TourHelper.js
src/files/explore-form/FilesExploreForm.js
src/lib/tours.js
src/peers/PeersTable/PeersTable.js
src/settings/SettingsPage.js
src/settings/Title.js
src/status/Commons.js

- Upgrades ipfs-css to 1.0.0
- Changes assorted `aqua` text and backgrounds to `teal` for accessibility contrast purposes
Note that this does change the overall tone of the look/feel subtly. We may want to think about adding more `teal` back in to non-accessibility-critical elements like borders and highlights in future work.
Closes https://github.com/ipfs-shipyard/ipfs-webui/issues/1379

Accessibility contrast fixes

---

.circleci/config.yml

For some reason unit tests fail on CI, low hanging fruit is to update CI to Node 12.x

fix: switch CI build to Node 12.x

---

README.md

I just made `v2.8.0` and wrote down steps that @rafaelramalho19 can reuse for future releases of IPFS Web UI.
Old ones were either outdated, missing details  or not very safe (like pushing all tags).
Let me know if something is unclear, could be worded better or I missed anything.
(Ignore CI for now - it is unrelated to this PR)

docs: update release steps

---

package-lock.json
src/lib/languages.json

Looks like language choices were displaying as "English" in the choose-language modal due to their being missing from `languages.json`.
- If it's a matter of having just forgotten to update the contents of `languages.json` after manually running `lol`, this PR addresses that.
- If `lol` is being run automatically and updating `languages.json` as some part of our deploy process, and I missed that, there's a larger problem as of yet unresolved.
Closes https://github.com/ipfs-shipyard/ipfs-webui/issues/1471

fix: updated languages.json using lol

---

public/locales/en/files.json
src/components/loading-animation/LoadingAnimation.js
src/files/files-list/FilesList.js

This is a fix for UX issue raised by @mirorauhala on Transifex:
>  Should be 'Name' since the list also lists folders. Makes it very
>  confusing that the column name is 'File name' yet it also lists folders
>  that aren't files.

fix(i18n): 'File name' → 'Name'

---

src/components/shell/Shell.js
src/status/BandwidthStatsDisabled.js
src/status/StatusNotConnected.js
src/welcome/WelcomePage.js

So, this is a nifty pick, but it was bugging me out having to remove the `$` sign every time I copied a shell command. So I made it not selectable 😄 
I also made the shell component responsive, which helped in some viewports: 
Here's the interaction:

fix: improve shell component ux

---

package-lock.json
public/locales/ca/peers.json
public/locales/cs/files.json
public/locales/de/files.json
public/locales/en/settings.json
public/locales/es/explore.json
public/locales/es/files.json
public/locales/es/peers.json
public/locales/fr/files.json
public/locales/it/explore.json
public/locales/it/files.json
public/locales/it/peers.json
public/locales/it/settings.json
public/locales/it/status.json
public/locales/it/welcome.json
public/locales/zh-CN/files.json
public/locales/zh-HK/files.json
public/locales/zh-TW/files.json
src/components/language-selector/language-modal/LanguageModal.js
src/i18n.js
src/lib/languages.json

This PR:
- synchronizes translations
- adds Catalan locale
- adds link to IPFS Translation Project at Transifex to the `LanguageModal`
- should improve the discoverability for people who want to add/improve translations

feat(i18n): sync, add `ca` and link to translation project 

---

test/e2e/peers.test.js
test/e2e/setup/test-environment.js

This PR bumps timeout in E2E tests of Peers screen to 30s and closes #1507

fix(ci): increase timeout for E2E Peers screen tests

---

src/bundles/peer-locations.js

In the `Peers` page, I got this error:
Sometimes, `bootstrapPeers` can be null so we should test it.
I have this error when I run an Go embedded Ipfs node on mobile.
Signed-off-by: remi <remi@berty.tech>

fix: bootstrapPeers can be null

---

package-lock.json
package.json
test/e2e/jest.config.js
test/e2e/setup/global-after-env.js

This PR:
- bumps puppeteer deps to latest versions
- **sets global timeout to 30 seconds** to avoid false-negatvies on slow CI setups
- this should be a generic fix for #1507  that applies to all current and future test scripts

chore: update puppeteer

---

test/e2e/explore.test.js
test/e2e/files.test.js
test/e2e/navigation.test.js
test/e2e/peers.test.js
test/e2e/settings.test.js
test/e2e/setup/global-after-env.js
test/e2e/setup/test-environment.js
test/e2e/status.test.js

This PR takes #1518 even further: ensures we wait as long as needed for a full page load,  all necessary DOM elements, and set globaltimeout of 30s for jest and expect libs used in e2e tests.
If CI is green, I am merging this so js-ipfs and go-ipfs take advantage of this.

fix(ci): more robust e2e

---

src/welcome/WelcomePage.js

Currently, the "API Not Connected" Error does not give the complete list of origins that need to be added to the IPFS settings according to the README.
This PR brings the In-App CORS instructions up to par with the README.
Haven't tested.

chore: update In-App CORS instructions to match README

---

public/locales/en/files.json
public/locales/ko-KR/files.json
public/locales/sv/files.json
src/files/info-boxes/welcome-info/WelcomeInfo.js

- Removes the files screen's "manage files" link to itself when displaying no-files-here welcome text
- Changes "You can drag and drop ..." to "Drag and drop here ..."
- Fixes an it's/its typo
Closes https://github.com/ipfs-shipyard/ipfs-webui/issues/1530

Remove self-ref files page link in "no files" screen

---

src/welcome/WelcomePage.js

This PR removes error in console  when there is no API available:

fix: console error when no API available

---

src/App.js
test/e2e/navigation.test.js

Pipeline was failing sometimes https://app.circleci.com/pipelines/github/ipfs-shipyard/ipfs-webui/301/workflows/7d739c8e-9f97-4ad9-a870-fb889442f7d9/jobs/4074 saying that "Explore" link was not clickable. 
I think it was because the window used by the CI was too small, hiding the element.
Hopefully this PR fixes it, will rekick the pipeline a couple of times to make sure 🙏

fix: responsive navbar on small devices

---

.github/workflows/publish_build.yml

I wanted to consume this software downstream for a Docker image, but the build process is a bit heavy. 
This logic pushes a tarball to a release when published. 
You can see an example on my fork here: 
https://github.com/thelamer/ipfs-webui/releases/tag/v2.10.2
https://github.com/thelamer/ipfs-webui/runs/855791405?check_suite_focus=true
You don't need to setup anything on the repo, merging this will push tarballs for all subsequent releases made after merge. 
I understand the value of pushing stuff like this to IPFS but in the case of software ingestion from your repo, the whole world conventionally hits the latest release api on github and pulls in on new release tags. Having this build asset transparently built in Github greatly simplifies this process. 
Let me know if you have any …

add logic to build and publish a tarball on release

---

src/explore/ExploreContainer.js

Closes https://github.com/ipfs-shipyard/ipfs-webui/issues/1490
Removing the `gatewayUrl` prop just allows for `ipld-explorer-component` to use the default one (`https://ipfs.io`)

fix: make explore page 'view on gateway' point to gateway

---

public/locales/en/files.json

The label does not match UI (button was renamed to "Import" a while ago):
> ![2020-07-28--21-48-53](https://user-images.githubusercontent.com/157609/88714144-a6720080-d11c-11ea-967e-cb9cbab2b62f.png)

fix: update Import button name

---

src/peers/WorldMap/WorldMap.js

This PR makes the following changes to how the peers map is displayed:
- Updates effective breakpoint in `WorldMap.js` to 960px, to match the tachyons breakpoint that forces nav menu to top of screen (NOTE this is slightly unrelated to original issue, but tidies the landscape for thinking about this)
- Adds a "height breakpoint" of `window.innerHeight < 940` to address concerns raised in https://github.com/ipfs-shipyard/ipfs-webui/issues/1561 for users with small laptops
- If window height is less than 940px, map height is 0.6 * window height, minus 180px allowance for furniture (search bar and "Add connection" button)
Note that to make this totally seamless for everyone, all the time, we'd really need to pull the peers page apart entirely and do something much more clever with truncating …

bug: tweak map height for sub-940px-high windows

---

package-lock.json
package.json
src/bundles/peer-locations.js

Closes https://github.com/ipfs-shipyard/ipfs-webui/issues/1603.
- Bumps `ipfs-geiop` to v5.0.1
- Bumps `geoipCache` in `peer-locations.js` to avoid cache discrepancies (United States vs USA) as described in https://github.com/ipfs-shipyard/ipfs-webui/issues/1603#issuecomment-684784369 
See screenshot:

chore: update ipfs-geoip

---

src/bundles/ipfs-provider.js

Closes #https://github.com/ipfs-shipyard/ipfs-webui/issues/1618

fix: fast pin.ls check

---

.circleci/config.yml

similar to https://github.com/ipfs/ipfs-docs/pull/195
When CI/CD runs and generates a CID, we need to pin that CID directly to the Websites (collab) cluster. Otherwise, when CircleCI's build finishes, the ipfs instance will dissapear and the CID will be irretrievable.

Have CI publish to the Collab Cluster

---

src/lib/files.js

This PR restores _Download_ feature when a single folder is selected.
https://github.com/ipfs-shipyard/ipfs-webui/issues/1576  missed one edge case, this fixes that + adds comments why we need POST.

fix: restore download of a single folder

---

src/files/files-list/FilesList.js

Fixes https://github.com/ipfs-shipyard/ipfs-webui/issues/1621

fix: files pin status now shows correctly

---

.tx/config

This ensures translations for `app.json` and `notify.json` will be fetched when `tx pull -a` is executed and translation is at least 75% complete.
Closes #1636

fix(i18n): sync app.json and notify.json

---

src/files/explore-form/FilesExploreForm.js

As mentioned in https://github.com/ipfs-shipyard/ipfs-webui/issues/1636#issue-702818983:
> In the search bar on top "Qmhash" should be switched to "bafyHash" or "IPFS CID" or "CID"?
This PR adds a reference to `bafy` hashes as depicted below. Happy to haggle over the text.

chore: update hint text in browse bar

---

.github/workflows/publish_build.yml

This is a tiny fix for https://github.com/ipfs-shipyard/ipfs-webui/pull/1543 to produce deterministic build based on `package-lock.json`
@thelamer @olizilla  does this sound good, or am I missing some context behind going with `npm install`?

chore(ci): use npm ci

---

package-lock.json
package.json
public/locales/en/files.json
src/files/FilesPage.js
src/files/file-preview/FilePreview.js

Closes #1642 
Closes #1647
Important info: https://github.com/achingbrain/uint8arrays#tostringarray-encoding--utf8
- Did `ipfs.cat` start returning uint8arrays recently?
- Do we need to parse uint8arrays in another function?

fix: allow json and text fiels to be in preview file component

---

public/locales/en/app.json
src/components/definition/Definition.js
src/navigation/NavBar.css
src/navigation/NavBar.js
src/status/NodeInfo.js

Closes https://github.com/ipfs-shipyard/ipfs-webui/issues/1650.
Closes https://github.com/ipfs-shipyard/ipfs-webui/issues/1649.
This PR ...
- Adds WebUI version number (linked to appropriate release page on GitHub) on both the nav (at widths wide enough for nav to appear at page left) and the Status screen
-  Tightens left-nav formatting to improve display for smaller 16x9 format screens (as identified in https://github.com/ipfs-shipyard/ipfs-webui/issues/1649#issuecomment-699055376), primarily to preserve display of version/revision/repo/bug-report links at nav bottom for 640+ high windows
**Big thanks to @bertrandfalguiere for raising these issues and PRing an initial fix!**
**Screenshot**
Mac Chrome, 660px high, new version on the right:

feat: add version info in nav and Status screen, tighten nav accordingly

---

src/bundles/files/actions.js
src/files/file-import-status/FileImportStatus.js

This fixes https://github.com/ipfs-shipyard/ipfs-webui/issues/1659, I would like to figure out how to automate tests for that issue, but I also don't want to block release so submitting this now & will try to figure out how to test in the followup.
According to @jessicaschilling we expect that when you drop or select `n` files for importing it would show "Importing n items" and once import is done show "Imported n items", however if you drop / select a file and a directory of n files it should show "Importing 2 items" and later "Imported 2 items" (Unless you had more items imported prior).
However code seemed to count number of import tasks for showing "importing n items" and then counting number of total files for showing "Imported n items", so neither was correct. Additionally …

fix: import / importing items count

---

src/navigation/NavBar.css
src/navigation/NavBar.js

Closes https://github.com/ipfs-shipyard/ipfs-desktop/issues/1668 (but requires release of webui).
- Makes room for Electron window furniture (top left) vis-a-vis logo when used in IPFS Desktop
- Maintains the 640px+ (aka 40em in our height system) behavior requirement outlined in https://github.com/ipfs-shipyard/ipfs-webui/pull/1654: preserves display of version/revision/repo/bug-report links at nav bottom for 640+ high windows
- Enhancement: Adds a "height breakpoint" for condensing left-nav elements at windows shorter than 49em (see screenshot)
- Behavior at different heights remains unchanged if window is narrower than 60em (aka width breakpoint for moving the nav to the top of the window)
Eyeballed as OK in Web UI in Mac Chrome, Firefox, and Safari. 
Gif demonstration (Mac Firefox): …

feat: better left navbar response at varying heights

---

package-lock.json
package.json

This PR updates ipfs-geoip dependency which brings the latest geoip dataset (`GeoLite2-City-CSV_20201013`)
See https://github.com/ipfs-shipyard/ipfs-geoip/pull/80 for more details.
Closes #1249
My node is located in Poland. I no longer see "USA" nodes with 30ms ping  –   faster-than-light networking is no more ;)
With this updated dataset, we now see much better distribution across all continents:

feat: updated geoip dataset (2020-10-13)

---

src/files/header/Header.js

Closes https://github.com/ipfs-shipyard/ipfs-webui/issues/1677.
Improvements to the legends in the Files page repo stats box:
- Uppercases to account for noun-capitalized languages (e.g. German)
- Improves text contrast for better legibility
- Uses link-blue text for consistency in link behavior
- Changes font to Montserrat for visual consistency
**Screenshot** (Mac Chrome):
Note: In the longer term, would like to add hover underline for all links throughout UI, but that's a matter for a separate PR.

fix: uppercase & standardize repo stats display

---

package-lock.json
package.json
public/locales/en/settings.json
src/components/language-selector/LanguageSelector.js
src/index.css
src/lib/tours.js
src/settings/SettingsPage.js

Closes https://github.com/ipfs-shipyard/ipfs-webui/issues/1514.
**This PR updates the react-joyride tour boxes on the Settings screen to bring this screen up to date for pinning service integration.**

feat: update Settings screen react-joyride for pinning services & tutor mode

---

public/locales/en/app.json
public/locales/en/files.json
public/locales/en/settings.json
src/bundles/files/consts.js
src/components/cli-tutor-mode/CliTutorMode.js

Closes https://github.com/ipfs-shipyard/ipfs-webui/issues/1686.
This PR separates out the i18n key `cliModal.extraNotes` so we can display different CLI Tutor Mode modal helptext in different situations:
- "IPFS Config" modal (already existed)
- "Set Pinning" command in Files screen context menu (new in this PR)
**To do:**
The i18n keys are split out, but I'm missing something that's probably obvious in terms of getting helptext to display when a tutor-mode modal is invoked from the context menu. @lidel or @rafaelramalho19, do you mind a quick look if you get the chance? 🙏

feat: separate CLI Tutor Mode helptext

---

src/files/modals/Modals.js

- Reads modals root prop to insert current MFS path in CLI command of tutor mode
- Applied for all import commands at file menu
Closes #1601

refactor(tutor-mode): Added CLI subdirectories

---

src/components/tooltip/Tooltip.js
src/files/file/File.js

This PR fixes the problem of displaying long file names when hovering the file.
- Set break-word property to tooltip.
- Changed overflow of rows to visible.
- Set tooltip width to not exceed the menus width.
Fixes: #1464

fix(line-wrap): Fixed tooltips of file names

---

src/components/text-input-modal/TextInputModal.js

This PR adds a default trim to `TextInputModal` and it should improve kind of user experiences.
Like below:
`before`:
`after`:

fix: trim input of "Import from IPFS"

---

package-lock.json
src/components/address/Address.js

This PR Closes #1593  and closes #1674

feat(peers): /dnsaddr/ support

---

src/components/details/Details.js

Fixes https://github.com/ipfs/ipfs-webui/issues/1693

fix: clicking in advanced section content no longer closes it

---

src/settings/SettingsPage.js

Closes https://github.com/ipfs/ipfs-webui/issues/1734

 fix: pinning services description

---

src/App.js
src/bundles/files/actions.js

Seems that this never worked with drag&drop because webui used path from URL as-is.
This PR fixes it by using url-decoded `realPath` after being processed by `src/bundles/files/utils.js#infoFromPath` 
Closes https://github.com/ipfs/ipfs-webui/issues/1733

fix: dnd to a dir with escaped characters

---

src/bundles/analytics.js
src/bundles/analytics.test.js

- Saying no to analytics explicitly calls `Countly.opt_out`. Without this removing all consents triggers a "consent removed" event to be tracked which is not what we want.
- Removing all individual consents explicitly calls `Countly.opt_out`
- Granting consent for 1 or more analytic types opts back in to analytics by calling `Countly.opt_in`.
- Saying yes to analytics explicitly calls `Countly.opt_in`, for completeness.
ref: https://github.com/ipfs/ipfs-webui/issues/1041#issuecomment-825770656
License: MIT

fix: do not send consent removal event

---

src/i18n.js

This ensures localStorage cache provided by `i18next-localstorage-backend` is not shared across webui versions.
Should close   https://github.com/ipfs/ipfs-webui/issues/1765

fix(i18n): cache per version

---

src/bundles/pinning.js
src/components/pinning-manager/PinningManager.js

This is a temporary workaround that maintains most of the functionality while being compatible with `pin remote` and `config` commands in go-ipfs 0.8.0:
- when service is added via webui, we replace `.` with `_` so the issue (#1770) never surfaces
- if service with `.` in name was already added or is added via CLI, we disable button for enabling auto upload of MFS, because it is not possible to make it work in go-ipfs 0.8.0, but everything else works as expected (manual pinning to "nft.storage" works fine)
Closes  #1770 (but we will have a separate fix in go-ipfs to support `.` in key names)
@alanshaw just for completeness, would it be ok for you to change `nft.storage` to `nft-storage` on https://nft.storage docs about `pin remote service add`?

fix: work around dot in pin service name

---

package-lock.json
src/files/FilesPage.js

Abort download was being called right after starting to fetch data, because if useState receives a function that function is called to get the final value.
To fix the issue we just wrap the abort function with another function.
closes #1783

fix: fix download files feature

---

public/locales/en/settings.json

This PR renames "Secret API key" to "Secret access token" to align better with terminology uses in https://ipfs.github.io/pinning-services-api-spec/ and reduce confusion described in https://github.com/ipfs/ipfs-webui/issues/1786#issuecomment-841577866.
>  ![2021-05-20--18-57-08](https://user-images.githubusercontent.com/157609/119019208-3c716300-b99d-11eb-8d34-4557787d942c.png)
Closes #1786
@obo20 @ipfs/wg-pinning-services any concerns?

style: Secret Access Token label

---

src/components/text-input-modal/TextInputModal.js
src/files/modals/add-by-path-modal/AddByPathModal.js

Closes #1775 my moving fix from #1718 to be applies only to "import from ipfs" modal.

fix: allow spaces in rename modal

---

package-lock.json
package.json
src/components/pinning-manager/PinningManager.js
src/files/file-import-status/FileImportStatus.js
src/files/file/File.js
src/files/header/Header.js
src/files/modals/pinning-modal/PinningModal.js
src/files/selected-actions/SelectedActions.js
src/lib/files.js
src/status/NodeBandwidthChart.js
src/status/PeerBandwidthTable.js
src/status/Speedometer.js
src/status/StatusConnected.js
test/e2e/files.test.js

This cleans up code around human-readable units and Closes #1778:
- base-2 (GiB, MiB, KiB) used for file sizes to remove any unit confusion while keeping interop with 1024  way of thinking 
> ![2021-05-20--00-34-50](https://user-images.githubusercontent.com/157609/118893775-4ba3d280-b903-11eb-8b59-a34ffd609834.png)
- base-10 (Mbps, kbps) used for network bandwith, to match what the number that ISP is selling:
> ![2021-05-20--00-14-20](https://user-images.githubusercontent.com/157609/118893056-1e0a5980-b902-11eb-931d-06018f5e8247.png)
@jessicaschilling  @olizilla would appreciate sanity check from your end. What units are expected by people these days? I've heard that macOS switched sizes in Finder to base-10, is that true?

fix: cleanup size and bandwidth units

---

src/bundles/files/actions.js

This removes the call to `ensureMFS` in `doFilesShareLink` to fix and close https://github.com/ipfs/ipfs-webui/issues/1744
I wasn't able to run the e2e tests on my machine, so we'll see if anything complains in CI, I guess :)
cc @lidel

remove ensureMFS call when generating share link

---

src/bundles/node-bandwidth-chart.js
src/status/NetworkTraffic.js
src/status/NodeBandwidthChart.js
src/status/Speedometer.js

...in some scenarios. it's a stacked graph, so the total height is in+out, when out is tiny and in is large it is not obvious that out is a tiny sliver stacked on top.
fixes #1797
License: MIT

fix: move output below input to be less confusing

---

public/locales/en/settings.json
src/components/pinning-manager/pinning-manager-modal/PinningManagerModal.js
src/components/pinning-manager/pinning-manager-service-modal/PinningManagerServiceModal.js

This PR adds a link to docs next to "Secret access token", making it easier for users of predefined services like Pinata to learn how to generate a new token. 
The link to docs is defined in https://github.com/ipfs/ipfs-webui/blob/dadaf04219f2cc38118ddcde48f4b42fb1de2643/src/constants/pinning.js#L9
>  ![2021-06-24--23-52-20](https://user-images.githubusercontent.com/157609/123337588-bae69500-d547-11eb-8eda-155793ff3bbb.png)

feat: link to pinning service docs if available

---

src/bundles/files/actions.js

This fixes dir size calculation when there was more than 100 items in a dir:
- we now skip size fetching only when there is more than 1000 dirs 
- size calculation is performed only once and memoized per CID, reducing the number of sent htt requests
Closes https://github.com/ipfs/ipfs-webui/issues/1805
Closes https://github.com/ipfs/ipfs-webui/issues/1687

fix: dir sizes in big dirs

---

src/bundles/files/actions.js
src/lib/files.js

Fixes #1829.
I went with a simpler approach than https://github.com/ipfs/ipfs-webui/issues/1814#issuecomment-873000366 (suggested fix) because the API is POST-only, so creating a link and then "opening" it would have returned a 405 error.
When https://github.com/ipfs/go-ipfs/issues/8234 is merged, #1814 can be addressed. In the meanwhile, #1829 is easily fixed.
The failing tests are the same as in the main branch.
License: MIT

fix: download directories outside of MFS

---

src/files/file-preview/FilePreview.js

Fixes #1809 by changing the drag layer to the inside of `PreviewItem` (renamed `Preview`). Now the dragging only applies to images, videos, audio and PDFs.
With this, I also removed the part of the class `className={ classNames(type !== 'pdf' && type !== 'text' && type !== 'json' && 'dib') }`. It didn't seem to change anything in practical terms. /cc @rafaelramalho19 any reason why was that added?
License: MIT

fix: selection for text files

---

src/bundles/pinning.js
src/components/pinning-manager/PinningManager.js
src/components/pinning-manager/pinning-manager-service-modal/PinningManagerServiceModal.js

Fixes #1816: now, when the input changes, we clear the errors from the form. The issue was that `handleSubmit` was not calling our actual `onSubmit` function since there were validation errors.
Regarding the second issue described by OP in https://github.com/ipfs/ipfs-webui/issues/1816#issuecomment-882104784, I could not reproduce.
License: MIT

fix: frozen pinning service modal error

---

src/bundles/ipfs-desktop.js
src/components/language-selector/language-modal/LanguageModal.js

Goes with https://github.com/ipfs/ipfs-desktop/pull/1894.
I think language switching wasn't even working at all because we're not using the localStorage anymore and IPFS Desktop simply had a wrapper around the localStorage.setItem function. Now it's more explicit and does not have room for many mistakes.
License: MIT

fix: update desktop language

---

src/settings/SettingsPage.js

Disable the API address form on IPFS Desktop.
Implements the first TODO from https://github.com/ipfs/ipfs-desktop/issues/1888#issuecomment-898472573
Note: this is needed: https://github.com/ipfs/ipfs-desktop/pull/1894
License: MIT

fix: do not show api address form on Desktop

---

src/bundles/gateway.js
src/components/public-gateway-form/PublicGatewayForm.js

Closes #1844 by using the same code we use in Companion (check mentioned issue).
It verifies if the gateway is valid only when submitting. I feel like validating on change would be better in terms of UX, but it can also be problematic as we have a 15 seconds timeout to account for the gateway to fetch the actual content.
License: MIT

feat: check if gateway is valid using image

---

src/navigation/NavBar.js

These links at the bottom:
Currently redirect does not work for `Revision` link and we get 404 page there.

Fix navbar links to the github repo.

---

src/bundles/files/actions.js
src/bundles/files/utils.js
src/files/modals/Modals.js

`.substr` is deprecated: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr
License: MIT

fix: replace .substr by .substring

---

src/lib/files.js

fix: download HAMT-sharded directories

---

package-lock.json
public/locales/en/notify.json
src/bundles/files/actions.js
src/bundles/notify.js
src/bundles/pinning.js
src/components/notify/Notify.js
src/components/pinning-manager/PinningManager.js
src/files/FilesPage.js
src/files/file/File.js
src/files/files-list/FilesList.js
src/files/modals/pinning-modal/PinningModal.js
src/files/modals/remove-modal/RemoveModal.js

This is bare minimum to restore remote pinning with rate-limited Pinata and close #1900
Not a perfect solution, but a fast-tracked fix to restore pinning functionality **_at all_** (right now Pinata is effectively broken in webui and ipfs-desktop – details in https://github.com/ipfs/ipfs-webui/issues/1900#issuecomment-1032030124).
Key changes:
- we progressively build a cache with remote pin states every time user opens "Set pinning" modal, and send requests only for files that we did not check the remote state before
- we persist  the `pinning` bundle state with remote pin states with  `createCacheBundle` (src/bundles/index.js) and `persistActions` (src/bundles/pinning.js), which store data in browser's IndexedDB (uses `money-clip` as cache backend)
- new users should not see any …

refactor: on-demand remote pin status checks

---

package-lock.json
package.json
src/bundles/files/consts.js
src/bundles/files/index.js
src/bundles/files/protocol.ts
src/bundles/files/selectors.js
src/bundles/pinning.js
src/components/pinning-manager/PinningManager.js

Fixes #1906: regression introduced in #1903, specifically by removing [local pin size calculation](https://github.com/ipfs/ipfs-webui/pull/1903/files#diff-7898dde76b2bbdcbb1d0fd5916ea316d6e7344901f01cbf5adb1822e140bc053), which is tied with the update of the amount of local pins.
Instead of just partially reverting the code, I added it to the pinning bundle and simplified, renamed and cleaned a few things.

fix: fetch local pins stats

---

src/files/explore-form/FilesExploreForm.js

I run my browser with a non-standard text size and I noticed that the `FilesExplorerForm` icons do not look correct. This changes the icon heights to relative units from the absolute (default) pixels.
Very small and very large text sizes *before* this change:
After:
I am using the Dark Reader extension for the dark theme. It is not part of this PR.

fix: FilesExplorerForm icons for differing browser text sizes

---

.github/workflows/ci.yml
package-lock.json
public/locales/en/app.json
src/bundles/files/actions.js
src/bundles/files/consts.js
src/files/FilesPage.js
src/files/context-menu/ContextMenu.js
src/files/context-menu/ContextMenu.stories.js
src/lib/files.js

Partially addresses #1798.
License: MIT

feat: download as CAR via the context menu 

---

src/files/FilesPage.js
src/lib/files.js

In #1894 we tried to address #1887. However, doing that for all types of files is [blocked](https://github.com/ipfs/ipfs-webui/pull/1894#discussion_r786341423) by https://github.com/ipfs/go-ipfs/issues/7746. This PR does the same but only for standalone files. I think it's a good improvement and can mitigate the issues that we are trying to address.
I also don't understand why the CI is failing on "Installing Dependencies" as this PR changes nothing regarding dependencies.

fix: use gateway links to download standalone files

---

package-lock.json
package.json

This PR updates ipfs-geoip dependency to the latest version, which brings the latest geoip dataset (`GeoLite2-City-CSV_20220628`)
The old one was 2 years old (!). – see https://github.com/ipfs-shipyard/ipfs-geoip/pull/88 for more details.
This should fix bugs  on Peers screen where it currently lists faster-than-light nonsense  like 8ms from Europe to USA ;-) 
> ![2022-06-29_05-43](https://user-images.githubusercontent.com/157609/176346785-c15618d1-2c64-4bb9-89e4-978f80ae02c4.png)

fix: updated ipfs-geoip (2022-06-28)

---

.github/workflows/tx-pull.yml

This github action, .github/workflows/tx-pull.yml, will
1. automatically pull translations
2. automatically create a commit to a `tx-pull-<github_sha>` branch
3. automatically open a PR from that branch to the main branch

chore: pull transifex translations automatically

---

.github/workflows/ci.yml
package.json

After enabling automated releases for this repo, I noticed a number of issues:
1. The car file was not attached to the GitHub release notes
2. Releases are generated for every single commit, causing release notes to become useless. We should batch commits and release only after a minimum wait time 
* I'm going to revert to creating a release manually, except all that will be required is running https://github.com/ipfs/ipfs-webui/actions/workflows/ci.yml (i.e. `workflow_dispatch`). This is still a significant improvement upon the previous manual process
3. Even though semantic-release doesn't publish to npm currently (we have it disabled), the files being added to the npm tarball were unnecessary (.cache/*, and many others. You can see this on old runs). This was making the logs extremely …

fix: resolve issues with automated releases 

---

package-lock.json
package.json

Added classnames to package.json to resolve this issue https://github.com/ipfs/ipfs-webui/issues/1976

added classnames to package.json

---

.github/workflows/node-test.yml

badges should only update on runs from main branch

fix: nodejs readme badges

---

README.md

See #1940 and https://github.com/ipfs/ipfs-webui/issues/1940#issuecomment-1179603709 for more information

docs(readme): NodeJS version support info

---

public/locales/en/app.json
src/navigation/NavBar.js
src/status/NodeInfo.js

Addresses #1984 for now by removing the Web UI version. However, I think @SgtPooki should still take a look at it in order to have the current revision.

fix: remove web ui version and keep revision

---

public/locales/en/app.json
public/locales/en/files.json
src/components/progress-bar/ProgressBar.js
src/files/modals/publish-modal/PublishModal.js
test/e2e/ipns.test.js

Closes #1993
When it finishes publishing:
After clicking:
Then the icon goes back to normal after 2 seconds.

feat: ux improvements to publish modal

---

src/i18n.js

This should fix #1999. I just wonder if this is not something that happens in other languages too. For example pt -> PT-PT or pt -> PT-BR.

fix: korean detection

---

src/files/file/File.js
src/lib/files.js

fixes #2017.
please check https://github.com/ipfs/ipfs-webui/issues/2017#issuecomment-1235417557 for more context
`humanSize` already takes care of undefined. I added a case for null.

fix: show '0 B' instead of '-' for zero-length files

---

src/constants/pinning.js

Now that we have 4+ services (https://github.com/ipfs/ipfs-webui/pull/2026) we should always show them in random order, so we do not promote any specific one above others.
This PR:
-  adds a simple shuffle that ensures random order across app loads
- fixes `service endpoint should be provided without the /pins suffix` error for templates added in #2026

fix(settings): randomize pinning service templates

---

.github/workflows/ci.yml
.github/workflows/test-storybook.yml
.github/workflows/test-unit.yml
package.json

- test: add storybook coverage to codecov
- test: add unit test coverage to codecov

test: add unit&storybook coverage to codecov

---

package.json
src/peers/WorldMap/Map.js

`topojson` has been deprecated in favor of other packages
`topojson-client` is recommended for the two methods we were using: https://www.npmjs.com/package/topojson#manipulation-topojson-client
works

chore: replace topojson with topojson-client

---

.github/workflows/ci.yml

I propose to make kubo version used during CI workflow run configurable.
This would enable running the CI workflow for a specific kubo release. In particular, we could include a testing step in the release checklist that asks the release lead to kick off CI workflow in `ipfs-webui` to test if the new kubo release is OK.
- https://github.com/ipfs/ipfs-webui/actions/runs/3135588411
_This is related to https://github.com/ipfs/kubo/issues/9237_

ci: made the kubo version param CI workflow uses configurable

---

.github/workflows/ci.yml

Reverts ipfs/ipfs-webui#2032
Given the comment in https://github.com/ipfs/ipfs-webui/pull/2032#issuecomment-1278928440 and the fact that we do test kubo and ipfs-webui in kubo repository (https://github.com/ipfs/kubo/blob/1d5e46ac97dbd9862818b191517a4dc04186a26e/.circleci/main.yml#L325), we do not need the changes introduced in #2032.

chore: revert "ci: made the kubo version param CI workflow uses configurable"

---

src/bundles/peer-bandwidth.test.js

This is a quick band-aid to stop sleep from sometimes failing on CI 
See https://github.com/ipfs/ipfs-webui/issues/2065#issuecomment-1315933342 for more details.

chore(ci): fix flaky unit test

---

patches/multiaddr+8.1.2.patch

Kubo 0.18  (https://github.com/ipfs/kubo/issues/9417) will automatically listen on both `/quic` and new `/quic-v1`
Without this fix Status page would fail like https://github.com/ipfs/ipfs-webui/issues/2033
Ref. https://github.com/ipfs/kubo/issues/9410

fix: support /quic-v1

---

src/files/file-import-status/FileImportStatus.css
src/files/file-import-status/FileImportStatus.js
src/reset.css

Closes https://github.com/ipfs/ipfs-webui/issues/2030
(1st part of the demo is with mouse clicks, 2nd is with the keyboard navigation for accessibility)
https://user-images.githubusercontent.com/24696635/207647031-0ff21567-2c7e-4bfe-9cbd-5b6e7c90fe01.mov
- I changed `src/reset.css` to use `:focus-visible` instead of `:focus`, which makes the outline box around "tabbable" elements only appear with **KEYBOARD** and not **MOUSE** interactions.

fix: import status window UX

---

public/locales/en/status.json
src/App.js
src/bundles/analytics.js
src/bundles/analytics.test.js
src/components/analytics-banner/AnalyticsBanner.js
src/components/ask/AskToEnable.js
src/status/StatusPage.js

fixes: https://github.com/ipfs/ipfs-desktop/issues/2370
fixes: #2085 
- Updates  banner per discussion ([here](https://www.notion.so/pl-strflt/Metrics-Collection-and-Consent-Language-0d4059f11d4d474bb76d00539d778d8d#35482f9eef47464cb9efab8eaf7b4f8f)) and enables metrics on app load

fix: webui update metrics to opt-out by default (part of 2074)

---

src/status/NetworkTraffic.stories.js

I noticed that https://app.codecov.io/gh/ipfs/ipfs-webui/tree/main/src/status shows NetworkTraffic as having very light coverage and wanted to add a storybook story for it.

chore: add NetworkTraffic.stories.js

---

src/bundles/pinning.js

This fixes https://github.com/ipfs/ipfs-webui/issues/2080. I can't find any reason in the current code base for why `doFetchRemotePins` needs to repeat continuously, and doing so causes a periodic re-render that interrupts media playback in the file preview.

removed repeatedly refetching remote pins

---

src/bundles/analytics.js
src/bundles/ipfs-provider.js
src/bundles/retry-init.js
src/lib/guards.js
src/lib/guards.test.js
src/lib/hofs/functions.js
src/lib/hofs/functions.test.js
tsconfig.json

WIP.
fixes #1831
* Only send IPFS_INIT_FAILED event after 5 attempts
* Only send the IPFS_INIT_FAILED event once per app-load
* Stop the retry-init process after a certain number of attempts
Note: We can debounce these and send only 1 every 5 min or so, but we're in breach of our countly contract currently because IPFS_INIT_FAILED is currently sending 4.8MM of these events from IPFS Desktop and 2MM from IPFS Web UI.
We do not need this many events to know if things are failing. Knowing how many times IPFS_INIT_FAILED per app load will be a MUCH better metric for informing how successful the app is for our users.
This also means, when the app boots up, if the user changes the API endpoint, we won't send an additional IPFS_INIT_FAILED metric.  If we want to get a metric for this, we'll have …

fix: dont spam IPFS_INIT_FAILED events to countly

---

src/constants/pinning.js

[4EVERLNAD IPFS Pinning Service API docs](https://docs.4everland.org/storage/4ever-pin/pinning-services-api)
https://github.com/ipfs-shipyard/pinning-service-compliance/pull/287

feat: add 4EVERLAND to list of pinning service providers

---

.github/workflows/test-e2e.yml
config-overrides.js

e2e tests were failing due to sharding and lack of coverage found in some shards: https://github.com/ipfs/ipfs-webui/actions/runs/5650403570
This PR fixes that. It also batches some actions that *should* be batched.
* caches the test:build so all shard runs don't have to build before running
* caches the .nyc_output folder so all shard runs don't have to emit their own coverage
which should result in the e2e tests being faster overall.
**Successful run on SgtPooki/ipfs-webui**: https://github.com/SgtPooki/ipfs-webui/actions/runs/5651849593

fix(ci): e2e coverage

---

README.md
package-lock.json
package.json
src/bundles/identity.test.js
test/e2e/ipns.test.js
test/e2e/peers.test.js
test/e2e/remote-api.test.js
test/e2e/setup/ipfs-backend.js

cc ipfs/npm-kubo#51
cc ipfs/kubo#8959
@SgtPooki  this should be safe to merge :pray:

refactor: switch npm to kubo

---

.github/workflows/ci.yml
README.md

This PR aims to solve the problem described in https://github.com/ipfs/distributions/issues/1053 by switching DNSLink updating to the new tool like we did in https://github.com/ipfs/distributions/pull/1055

fix: switch to new dnslink updater

---

.github/workflows/build.yml
.github/workflows/ci.yml
.github/workflows/eslint.yml
.github/workflows/node-test.yml
.github/workflows/node-versions.yml
.github/workflows/test-e2e.yml
.github/workflows/test-storybook.yml
.github/workflows/test-unit.yml
.github/workflows/typecheck.yml
README.md

Also updates node-test badges and node versions tested.

chore: optimize CI caching

---

src/bundles/analytics.js
src/bundles/analytics.test.js
src/settings/SettingsPage.js
src/status/StatusPage.js

This PR applies minimal changes to Close #2198 but without waiting for https://github.com/ipfs-shipyard/ignite-metrics/issues/133
- hide analytics UI components
- stop sending broken opt-out metrics to instance which no longer works
It does not remove any code, and allows restoring analytics once we have time to do https://github.com/ipfs-shipyard/ignite-metrics/issues/133.

chore: disable countly analytics and hide unused UI

---

src/files/file-preview/FilePreview.js

content may be an empty string but`!"" === true` so it will use` ComponentLoader`, but we should load it as it has content(empty content)

fix: loading empty content

---

src/components/pinning-manager/fixtures/pinningServices.js
src/constants/pinning.js

Functionland Fula is an ipfs compatible DePIN network of 900 (as of 28/06/2024) individually owned and globally distributed nodes. The pinning service report is available at: [https://github.com/functionland/pinning-service/blob/main/api.cloud.fx.land.md](https://github.com/functionland/pinning-service/blob/main/api.cloud.fx.land.md)
Information on Functionland is avaialbe at https://fx.land and also https://www.crunchbase.com/organization/functionland/signals_and_news/timeline

feat(remotepins): add Functionland Fula

---

src/files/file-preview/FilePreview.js

This aims to sanitize localhost `src` url for embedded image/audio/video to avoid mixed-content warning in latest chrome-based browsers.
Rationale: https://github.com/ipfs/ipfs-webui/issues/2246#issuecomment-2322192398

fix(file-preview): safeSubresourceGwUrl

---

public/locales/en/files.json
src/bundles/files/actions.js
src/files/file-preview/FilePreview.js

- Closes #2217 by 
Can be tested with big txt file, like `bafybeicbevt3gr2jhs23f2sikwcqtirrhrdyscriutfg5mtlxoud55htii` 
> ![2024-08-31_02-14](https://github.com/user-attachments/assets/e84b5629-ca90-4d4c-93e5-4a56ac820f18)

fix(files): avoid duplicated fetch during preview

---

package-lock.json
package.json
src/App.js
src/bundles/ipfs-provider.js
src/bundles/local-storage.js

fix: set Explore defaults on app load
* sets localStorage settings required by ipld-explorer-components on app load
* disable remote gateways
* enable local gateways

fix: set Explore defaults on app load

---

cors-config.sh
public/locales/en/app.json
public/locales/en/notify.json
public/locales/en/status.json
public/locales/en/welcome.json
src/bundles/ipfs-provider.js
src/components/is-not-connected/IsNotConnected.js
src/settings/SettingsPage.js

This PR aims to finish our UX migration from "ipfs daemon" being IPFS, and making it explicitly clear that there is no "IPFS API", but we use "Kubo daemon" and "Kubo RPC API".
I also updated STDOUT example to reflect Kubo 0.30.
Many users are not aware that 99% of their interactions with IPFS depend on Kubo, and if things go wrong, they are not sure what "Kubo RPC" is.
This PR replaces "IPFS API" with "Kubo RPC" to make it more clear what components are at play, and what terms to use when looking for help.
> ![2024-09-18_17-55](https://github.com/user-attachments/assets/5cbf2496-d0bb-4d3d-8496-dc57ebbc8f0e)

fix(ui): replace IPFS API with Kubo RPC

---

src/files/FilesPage.js

In Files, the PDF viewer was re-rendering when interacting with web UI.
In [FilesPage.js](https://github.com/ipfs/ipfs-webui/blob/main/src/files/FilesPage.js), `MainView` is defined as a new component inside the `FilesPage` component, so clicking UI elements around the PDF re-renders `MainView` (and since `MainView` contains the logic that shows the file preview component, the preview re-renders). Issue seemed to only affect PDFs.
Fix: creating and using a new file preview component defined outside of `FilePages`. Not sure if this is the cleanest approach, so I'm open to suggestions!
Closes #2145 
https://github.com/user-attachments/assets/853c578d-d843-474a-9548-5314ac607bb9

fix: PDF viewer refreshes when interacting with web UI

---

config-overrides.js
package.json

fix: analyze script doesn't persist stats.json
Instead of generating a build/stats.json and then using the webpack-bundle-analyzer CLI, we run the server directly via the plugin options if BUILD_ENV=analyze.
Fixes #2289

fix: build script doesn't persist stats.json

---

src/lib/languages.json

Adds `lt` to languages.json so it passes unit tests. The first translations for this language was added in #2291

fix: add lithuanian to languages.json

---

.github/workflows/ci.yml

This was not a good idea when pinning to collab clusters...

Do not specify replication factor when pinning - use cluster's default

---

.github/workflows/ci.yml

Since we already have the CAR, add directly rather than waiting for bitswap upload.

ci workflow: Add CAR file directly to cluster

---

.github/workflows/ci.yml

This PR is backport of https://github.com/protocol/badbits.dwebops.pub/pull/48053
- Upload of <50MiB CAR with webui should take only a few seconds, everything more means something is really, really wrong
- It runs pinning to cluster in a loop, assuming pin should not take longer than 1 minute. 
- If the first attempt fails, follow-up ones will run with debug enabled to see which cluster node is picked and fails
- We retry up to 5 minutes
- We disable collab-cluster-am6-1.cluster.dwebops.net for now
cc @SgtPooki  @2color  for visibility

fix(ci): cluster pinning with timeout and retry

---

package-lock.json
package.json
src/bundles/peer-locations.js

https://github.com/ipfs-shipyard/ipfs-geoip/releases/tag/v9.2.0 updates Peers screen to use dataset from 2025-02-18.
This fixes most of invalid country flags that suggest libp2p is breaking the speed of light ;-)
- fixed Chrome bug on Peers screen (forcing `https://` on localhost redirect) in https://github.com/ipfs/ipfs-webui/pull/2333/commits/0310932cce5c8f038c5f1d2c29b0a69207070a16

fix(peers): chrome regression and update ipfs-geoip to v9.2

---

public/locales/en/app.json
public/locales/fi/app.json
public/locales/hu/app.json
public/locales/ja-JP/app.json
public/locales/ko-KR/app.json
public/locales/ur/app.json

This PR expands on https://github.com/ipfs/ipfs-docs/pull/2000 and aims to provide a hint that you can pass basic HTTP auth credentials in the webui.

fix: add hint about basic http auth for rpc

---

@types/ipfs/index.d.ts
package-lock.json
package.json
public/locales/en/app.json
public/locales/en/files.json
src/bundles/files/actions.js
src/bundles/files/consts.js
src/bundles/files/utils.js
src/files/FilesPage.js
src/files/file-input/FileInput.js
src/files/header/Header.js
src/files/modals/Modals.js
src/files/modals/add-by-car-modal/AddByCarModal.js
src/files/modals/add-by-car-modal/AddByCarModal.stories.js
src/lib/files.js

- Close  https://github.com/ipfs/ipfs-webui/issues/1798
- Add "Import CAR File", including
- Dropdown menu in import
- CAR File import modal with file input, optional name input and validation on file name by extension
- Add local definition of DAG from kubo to `IPFSService`

feat(files): CAR Import

---

src/constants/pinning.js

This PR removes Web3.Storage and Scaleway from WebUI and IPFS Desktop.
Remote Pinning APIs endpoints no longer work and docs return 404, and having those only confuse users of Kubo and IPFS Desktop.
> ![image](https://github.com/user-attachments/assets/7185bbeb-b69a-4381-b6bf-2314aae5f1b6)
cc for visibility:
- https://github.com/ipfs/ipfs-webui/pull/2026  @alanshaw @vasco-santos
- https://github.com/ipfs/ipfs-webui/pull/2132 https://github.com/ipfs/ipfs-webui/pull/2132 @OnsagerHe @vmscw

chore: remove web3.storage and Scaleway

---

.eslintignore
.eslintrc.cjs
src/bundles/files/protocol.ts

FYI that eslint was passing in CI because it runs before build, but when running locally i was getting hundreds of thousands of errors.. debugging with `DEBUG=eslint:cli-engine npm run eslint` showed that the build folder was being checked. when I removed that, it started succeeding again.
Also removed the ignoring of .ts files in the `.eslintrc.cjs` file

fix: eslint doesnt check build folder

---

.eslintrc.cjs
src/bundles/files/actions.js
src/bundles/files/consts.js
src/bundles/files/utils.js
src/bundles/ipns.js
src/bundles/pinning.js
src/files/FilesPage.js
src/files/context-menu/ContextMenu.js
src/lib/files.js
src/lib/files.test.js

This PR dispatches one-time extra announce of the root CID when sharing, copying CIDs, pinning, or publishing to IPNS.
Providing this CID costs us virtually nothing, but will improve performance when content is accessed by others shortly after these operations by ensuring we are as close to the desired number of Amino DHT peers with provider records as possible, and also that there ARE provider records for the root CID in the DHT in the first place.
The latter especially helps desktop users, who may share a CID that has not been provided yet due to the node being offline for a while and starting IPFS Desktop recently, with Kubo having many CIDs to announce.

feat: add async provide on share/copy/pin/ipns

---

src/bundles/analytics.js
src/bundles/analytics.test.js

Countly Morghulis!
Close #2334

fix: stop sending requests to defunct countly

---

src/components/box/Box.js

replaced `global.location.pathname` with `window.location.pathname` since `global` is only available in Node.js.
this resolves the runtime error in the browser and ensures correct path handling in the React app.

fix: reference to `global` in browser environment

---

src/files/file-preview/FilePreview.js

Long filenames in the file preview were causing horizontal scrollbars and breaking the layout. 
- Added smart middle truncation for filenames longer than 40 characters
- Shows the beginning and end with "..." in the middle (like `very-long-filename...layout.pdf`)
- File extensions stay visible so you always know the file type
The truncation is smart about preserving the most useful parts of the filename while keeping the layout clean.
**Screenshot**
https://github.com/user-attachments/assets/e395de24-5128-49f9-bd58-6a89ad7cf9ca
Fixes #2405

fix(FilePreview): prevent layout breaks with long filenames

---

src/bundles/gateway.js
test/e2e/grid-view.test.js
test/e2e/playwright.config.js
test/e2e/remote-rpc-api.test.js
test/e2e/settings.test.js

E2E tests were very flaky. This should stabilize them so its not necessary to re-run every PR.
- add safelisted test gateway URLs that bypass validation (was flaky due to real request to dweb.link)
- test invalid input first (red border) then valid (green border)
- remove explicit timeouts, use UI state-based waits instead (90s in CI is plenty, even if things are slow)
- fix flaky grid view folder navigation test
- increase CI test retries from 2 to 3 (just to be safe)

test: make e2e tests more robust
